import type { ComponentRegistryEntry } from "./types";
import { TECHNOLOGY_CATALOG } from "../technologies";

export const BUILTIN_ENTRIES: ComponentRegistryEntry[] = [
  {
    id: "database",
    label: "Database",
    color: "#6366f1",
    icon: "M4 7v10c0 2.2 3.6 4 8 4s8-1.8 8-4V7M4 7c0 2.2 3.6 4 8 4s8-1.8 8-4M4 7c0-2.2 3.6-4 8-4s8 1.8 8 4M4 12c0 2.2 3.6 4 8 4s8-1.8 8-4",
    category: "data",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "tables", label: "Tables", placeholder: "users, orders, products" },
      { key: "primaryKey", label: "Primary Key", placeholder: "id (UUID)" },
      { key: "sortKey", label: "Sort Key", placeholder: "created_at" },
      { key: "indexes", label: "Indexes", placeholder: "email_idx, status_idx" },
    ],
    technologies: TECHNOLOGY_CATALOG["database"],
    connectsTo: ["message-queue", "stream-processor"],
  },
  {
    id: "api-gateway",
    label: "API Gateway",
    color: "#f97316",
    icon: "M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5",
    category: "networking",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "authMethod", label: "Auth Method", placeholder: "JWT, API Key, OAuth" },
      { key: "rateLimit", label: "Rate Limit", placeholder: "1000 req/min" },
      { key: "cors", label: "CORS", placeholder: "*.example.com" },
    ],
    technologies: TECHNOLOGY_CATALOG["api-gateway"],
    connectsTo: ["service", "serverless", "container-orchestration", "api-gateway"],
  },
  {
    id: "service",
    label: "Service",
    color: "#22c55e",
    icon: "M5 3h14a2 2 0 012 2v14a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2zm3 4h2m-2 4h2m-2 4h2",
    category: "compute",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "endpoints", label: "Endpoints", placeholder: "GET /users, POST /orders" },
      { key: "replicas", label: "Replicas", placeholder: "3" },
      { key: "dependencies", label: "Dependencies", placeholder: "database, cache" },
    ],
    technologies: TECHNOLOGY_CATALOG["service"],
    connectsTo: [
      "database",
      "cache",
      "message-queue",
      "storage",
      "search-engine",
      "data-warehouse",
      "stream-processor",
      "webhook",
      "service",
    ],
  },
  {
    id: "cache",
    label: "Cache",
    color: "#a855f7",
    icon: "M13 2L3 14h9l-1 8 10-12h-9l1-8",
    category: "data",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "strategy", label: "Strategy", placeholder: "Write-through, Write-back" },
      { key: "ttl", label: "TTL", placeholder: "3600s" },
      { key: "eviction", label: "Eviction Policy", placeholder: "LRU, LFU" },
      { key: "maxSize", label: "Max Size", placeholder: "512 MB" },
    ],
    technologies: TECHNOLOGY_CATALOG["cache"],
    connectsTo: [],
  },
  {
    id: "message-queue",
    label: "Message Queue",
    color: "#eab308",
    icon: "M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z",
    category: "messaging",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "topics", label: "Topics", placeholder: "user.created, order.placed" },
      { key: "retention", label: "Retention", placeholder: "7 days" },
      { key: "deliveryMode", label: "Delivery", placeholder: "At-least-once, Exactly-once" },
      { key: "partitions", label: "Partitions", placeholder: "12" },
    ],
    technologies: TECHNOLOGY_CATALOG["message-queue"],
    connectsTo: ["service", "serverless", "stream-processor", "webhook"],
  },
  {
    id: "storage",
    label: "Storage",
    color: "#14b8a6",
    icon: "M3 3h7v7H3V3zm11 0h7v7h-7V3zM3 14h7v7H3v-7zm11 0h7v7h-7v-7z",
    category: "storage",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "bucketName", label: "Bucket / Path", placeholder: "s3://my-bucket" },
      { key: "replication", label: "Replication", placeholder: "Cross-region" },
      { key: "encryption", label: "Encryption", placeholder: "AES-256" },
      { key: "lifecycle", label: "Lifecycle", placeholder: "Archive after 90d" },
    ],
    technologies: TECHNOLOGY_CATALOG["storage"],
    connectsTo: ["serverless", "stream-processor"],
  },
  {
    id: "cdn",
    label: "CDN",
    color: "#ec4899",
    icon: "M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z",
    category: "networking",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "origins", label: "Origins", placeholder: "api.example.com" },
      { key: "cacheRules", label: "Cache Rules", placeholder: "static/* 30d" },
      { key: "edgeLocations", label: "Edge Locations", placeholder: "Global" },
    ],
    technologies: TECHNOLOGY_CATALOG["cdn"],
    connectsTo: ["load-balancer", "api-gateway", "storage"],
  },
  {
    id: "load-balancer",
    label: "Load Balancer",
    color: "#6366f1",
    icon: "M12 3v18m-7-7l7 7 7-7M5 8h14M8 5h8",
    category: "networking",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "algorithm", label: "Algorithm", placeholder: "Round Robin, Least Conn" },
      { key: "healthCheck", label: "Health Check", placeholder: "/health, 10s interval" },
      { key: "targets", label: "Targets", placeholder: "service-a, service-b" },
      { key: "protocol", label: "Protocol", placeholder: "HTTP, gRPC, TCP" },
    ],
    technologies: TECHNOLOGY_CATALOG["load-balancer"],
    connectsTo: [
      "service",
      "api-gateway",
      "serverless",
      "container-orchestration",
      "load-balancer",
    ],
  },
  {
    id: "firewall",
    label: "Firewall",
    color: "#ef4444",
    icon: "M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z",
    category: "networking",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "inboundRules", label: "Inbound Rules", placeholder: "443/tcp, 80/tcp" },
      { key: "outboundRules", label: "Outbound Rules", placeholder: "All traffic" },
      { key: "allowedIPs", label: "Allowed IPs", placeholder: "10.0.0.0/8" },
      { key: "waf", label: "WAF Rules", placeholder: "OWASP Top 10" },
    ],
    technologies: TECHNOLOGY_CATALOG["firewall"],
    connectsTo: ["load-balancer", "api-gateway", "service", "serverless"],
  },
  {
    id: "webhook",
    label: "Webhook",
    color: "#06b6d4",
    icon: "M15 7h3a5 5 0 015 5 5 5 0 01-5 5h-3m-6 0H6a5 5 0 01-5-5 5 5 0 015-5h3M8 12h8",
    category: "messaging",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "url", label: "URL", placeholder: "https://api.example.com/hook" },
      { key: "method", label: "Method", placeholder: "POST" },
      { key: "headers", label: "Headers", placeholder: "Authorization, Content-Type" },
      { key: "retries", label: "Retries", placeholder: "3 with exponential backoff" },
    ],
    technologies: TECHNOLOGY_CATALOG["webhook"],
    connectsTo: ["service", "serverless", "api-gateway"],
  },
  {
    id: "cron",
    label: "Cron",
    color: "#8b5cf6",
    icon: "M12 2a10 10 0 100 20 10 10 0 000-20zm0 4v6l4 2",
    category: "scheduling",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "schedule", label: "Schedule", placeholder: "0 */6 * * *" },
      { key: "command", label: "Command", placeholder: "node cleanup.js" },
      { key: "timeout", label: "Timeout", placeholder: "300s" },
      { key: "alertOn", label: "Alert On", placeholder: "Failure, timeout" },
    ],
    technologies: TECHNOLOGY_CATALOG["cron"],
    connectsTo: ["service", "serverless", "message-queue", "webhook", "database"],
  },
  {
    id: "client",
    label: "Client",
    color: "#f59e0b",
    icon: "M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2M12 3a4 4 0 100 8 4 4 0 000-8z",
    category: "client",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "platform", label: "Platform", placeholder: "Web, iOS, Android" },
      { key: "authFlow", label: "Auth Flow", placeholder: "OAuth 2.0 PKCE" },
      { key: "version", label: "Version", placeholder: "v2.1.0" },
    ],
    technologies: TECHNOLOGY_CATALOG["client"],
    connectsTo: ["api-gateway", "cdn", "load-balancer", "dns", "firewall"],
  },
  {
    id: "search-engine",
    label: "Search Engine",
    color: "#d97706",
    icon: "M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z",
    category: "data",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "indexName", label: "Index Name", placeholder: "products, articles" },
      { key: "queryType", label: "Query Type", placeholder: "Full-text, vector, hybrid" },
      { key: "replicas", label: "Replicas", placeholder: "2" },
      { key: "analyzer", label: "Analyzer", placeholder: "Standard, custom" },
    ],
    technologies: TECHNOLOGY_CATALOG["search-engine"],
    connectsTo: [],
  },
  {
    id: "dns",
    label: "DNS",
    color: "#0ea5e9",
    icon: "M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm-1-13h2v6h-2zm0 8h2v2h-2z",
    category: "networking",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "domain", label: "Domain", placeholder: "example.com" },
      { key: "recordTypes", label: "Record Types", placeholder: "A, CNAME, MX" },
      {
        key: "routingPolicy",
        label: "Routing Policy",
        placeholder: "Latency, weighted, geolocation",
      },
      { key: "ttl", label: "TTL", placeholder: "300s" },
    ],
    technologies: TECHNOLOGY_CATALOG["dns"],
    connectsTo: ["cdn", "load-balancer", "api-gateway", "firewall", "storage"],
  },
  {
    id: "serverless",
    label: "Serverless",
    color: "#f472b6",
    icon: "M13 10V3L4 14h7v7l9-11h-7z",
    category: "compute",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "trigger", label: "Trigger", placeholder: "HTTP, S3 event, schedule" },
      { key: "runtime", label: "Runtime", placeholder: "Node.js 20, Python 3.12" },
      { key: "memory", label: "Memory", placeholder: "512 MB" },
      { key: "timeout", label: "Timeout", placeholder: "30s" },
    ],
    technologies: TECHNOLOGY_CATALOG["serverless"],
    connectsTo: [
      "database",
      "cache",
      "message-queue",
      "storage",
      "search-engine",
      "data-warehouse",
      "stream-processor",
      "webhook",
      "serverless",
    ],
  },
  {
    id: "container-orchestration",
    label: "Containers",
    color: "#0891b2",
    icon: "M21 16V8a2 2 0 00-1-1.73l-7-4a2 2 0 00-2 0l-7 4A2 2 0 003 8v8a2 2 0 001 1.73l7 4a2 2 0 002 0l7-4A2 2 0 0021 16z",
    category: "compute",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "clusterSize", label: "Cluster Size", placeholder: "3 nodes" },
      { key: "namespace", label: "Namespace", placeholder: "production" },
      { key: "deployStrategy", label: "Deploy Strategy", placeholder: "Rolling, blue-green" },
      { key: "resources", label: "Resources", placeholder: "2 vCPU, 4 GB per pod" },
    ],
    technologies: TECHNOLOGY_CATALOG["container-orchestration"],
    connectsTo: ["service", "database", "cache", "message-queue", "storage", "serverless"],
  },
  {
    id: "stream-processor",
    label: "Stream Processor",
    color: "#10b981",
    icon: "M4 4h16v4H4zm0 6h16v4H4zm0 6h16v4H4z",
    category: "messaging",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "inputSource", label: "Input Source", placeholder: "Kafka topic, Kinesis stream" },
      { key: "outputSink", label: "Output Sink", placeholder: "S3, database, another topic" },
      { key: "windowType", label: "Window Type", placeholder: "Tumbling 5m, sliding 1m" },
      { key: "checkpointing", label: "Checkpointing", placeholder: "Every 60s" },
    ],
    technologies: TECHNOLOGY_CATALOG["stream-processor"],
    connectsTo: ["database", "data-warehouse", "storage", "message-queue", "service", "serverless"],
  },
  {
    id: "data-warehouse",
    label: "Data Warehouse",
    color: "#7c3aed",
    icon: "M4 7v10c0 2.2 3.6 4 8 4s8-1.8 8-4V7M4 7c0-2.2 3.6-4 8-4s8 1.8 8 4M4 7c0 2.2 3.6 4 8 4s8-1.8 8-4M4 12c0 2.2 3.6 4 8 4s8-1.8 8-4",
    category: "data",
    source: "builtin",
    planFields: [
      { key: "technology", label: "Technology", type: "technology" },
      { key: "tables", label: "Tables", placeholder: "fact_orders, dim_users" },
      { key: "partitioning", label: "Partitioning", placeholder: "By date, monthly" },
      { key: "compression", label: "Compression", placeholder: "Columnar, Zstd" },
      { key: "queryEngine", label: "Query Engine", placeholder: "SQL, Spark SQL" },
    ],
    technologies: TECHNOLOGY_CATALOG["data-warehouse"],
    connectsTo: [],
  },
];
