/**
 * Cron generator — hybrid.
 *
 * Emits two deterministic artifacts plus a focused bundle:
 *
 *   1. job.ts — entrypoint that calls work() with a hard timeout and
 *      surfaces failure as a non-zero exit so the scheduler retries
 *      or alerts.
 *   2. cronjob.yaml — Kubernetes CronJob manifest pinned to
 *      plan.schedule with the timeout encoded as activeDeadlineSeconds.
 *      The k8s CronJob shape is portable (also works as a config
 *      reference for non-k8s deploys).
 *   3. Bundle (README + prompt + validate.sh) asking the LLM to write
 *      ONLY work.ts (one function: the job body).
 *
 * Falls back to today's bundle behavior for non-Node languages — the
 * job.ts is TS-specific.
 */

import { emitBundle } from "../bundle";
import { buildServiceUserPrompt, buildSystemPrompt } from "../prompt";
import type { Generator, GeneratedFile, GeneratorContext } from "../types";

const FALLBACK_GUIDANCE = [
  "",
  "<cron>",
  "Scheduled job. Emit a job body that honors the schedule/timeout/alertOn hints,",
  "is idempotent across retries, and uses the clients in <available-clients>.",
  "</cron>",
].join("\n");

export const cronLLMGenerator: Generator = {
  kind: "hybrid",

  supports(ctx) {
    return ctx.node.componentType === "cron";
  },

  async generate(ctx: GeneratorContext): Promise<GeneratedFile[]> {
    const lang = ctx.language ?? "node";
    if (lang !== "node") {
      return emitBundle(ctx, {
        systemPrompt: buildSystemPrompt(lang),
        userPrompt: buildServiceUserPrompt(ctx) + FALLBACK_GUIDANCE,
      });
    }

    const plan = ctx.node.plan ?? {};
    const schedule = plan.schedule || "0 0 * * *";
    const timeoutSeconds = parseTimeout(plan.timeout);

    const job = renderJobTs(ctx, timeoutSeconds);
    const cronjob = renderCronJobYaml(ctx, schedule, timeoutSeconds);
    const prompt = buildWorkPrompt(ctx, job);

    const bundle = emitBundle(ctx, {
      systemPrompt: buildSystemPrompt("node"),
      userPrompt: prompt,
      expectedOutputs: ["work.ts", "work.test.ts"],
    });

    return [
      { path: "job.ts", contents: job },
      { path: "cronjob.yaml", contents: cronjob },
      ...bundle,
    ];
  },
};

function parseTimeout(raw: string | undefined): number {
  if (!raw) return 300;
  const m = raw.match(/(\d+)\s*([smh])?/i);
  if (!m) return 300;
  const n = parseInt(m[1], 10);
  const unit = (m[2] || "s").toLowerCase();
  return unit === "h" ? n * 3600 : unit === "m" ? n * 60 : n;
}

function renderJobTs(ctx: GeneratorContext, timeoutSeconds: number): string {
  return [
    `// Scheduled job entrypoint for "${ctx.node.label}".`,
    `// Skeleton generated by Arkon buildout (deterministic).`,
    `// Business logic in work.ts is LLM-generated.`,
    ``,
    `import { work } from "./work";`,
    ``,
    `const TIMEOUT_MS = Number(process.env.JOB_TIMEOUT_MS ?? ${timeoutSeconds * 1000});`,
    ``,
    `/**`,
    ` * Runs work() under a hard timeout. The scheduler decides retry`,
    ` * policy; we only enforce per-invocation duration here.`,
    ` *`,
    ` * Exit codes:`,
    ` *   0  — success`,
    ` *   1  — work() threw`,
    ` *   2  — timeout fired`,
    ` */`,
    `async function run(): Promise<void> {`,
    `  const start = Date.now();`,
    `  const ac = new AbortController();`,
    `  const timeout = setTimeout(() => ac.abort(), TIMEOUT_MS);`,
    `  try {`,
    `    await work({ signal: ac.signal });`,
    `    console.log(\`job ok in \${Date.now() - start}ms\`);`,
    `  } catch (err) {`,
    `    if (ac.signal.aborted) {`,
    `      console.error(\`job timed out after \${TIMEOUT_MS}ms\`);`,
    `      process.exit(2);`,
    `    }`,
    `    console.error("job failed", err);`,
    `    process.exit(1);`,
    `  } finally {`,
    `    clearTimeout(timeout);`,
    `  }`,
    `}`,
    ``,
    `run();`,
    ``,
  ].join("\n");
}

function renderCronJobYaml(
  ctx: GeneratorContext,
  schedule: string,
  timeoutSeconds: number,
): string {
  const name = ctx.node.label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 52) || "cron-job";

  return [
    `# Kubernetes CronJob for "${ctx.node.label}".`,
    `# Schedule and timeout pulled from the canvas plan fields.`,
    `# Replace TODO image with your container image.`,
    `apiVersion: batch/v1`,
    `kind: CronJob`,
    `metadata:`,
    `  name: ${name}`,
    `spec:`,
    `  schedule: "${schedule}"`,
    `  concurrencyPolicy: Forbid`,
    `  successfulJobsHistoryLimit: 3`,
    `  failedJobsHistoryLimit: 3`,
    `  jobTemplate:`,
    `    spec:`,
    `      activeDeadlineSeconds: ${timeoutSeconds}`,
    `      backoffLimit: 1`,
    `      template:`,
    `        spec:`,
    `          restartPolicy: OnFailure`,
    `          containers:`,
    `            - name: job`,
    `              image: TODO-${name}:latest`,
    `              command: ["node", "job.js"]`,
    ``,
  ].join("\n");
}

function buildWorkPrompt(ctx: GeneratorContext, jobSrc: string): string {
  const lines: string[] = [];
  lines.push(buildServiceUserPrompt(ctx));
  lines.push("");
  lines.push("<hybrid-skeleton>");
  lines.push(
    "The job entrypoint (`job.ts`) and the scheduler manifest (`cronjob.yaml`) " +
      "are already generated. job.ts runs `work()` under a timeout and surfaces " +
      "failure as a non-zero exit code. Your job is to write ONLY `work.ts` " +
      "(plus `work.test.ts`) — do NOT regenerate job.ts or cronjob.yaml.",
  );
  lines.push("");
  lines.push("Here is the `job.ts` you must match:");
  lines.push("```ts");
  lines.push(jobSrc.trimEnd());
  lines.push("```");
  lines.push("");
  lines.push("Implement in `work.ts`:");
  lines.push(" - `export async function work(opts: { signal: AbortSignal }): Promise<void>`");
  lines.push(" - Honor opts.signal — long-running fetches/queries should pass it through.");
  lines.push(" - Idempotent: a retry on the same schedule window must not double-process.");
  lines.push(" - Use ONLY the clients listed in `<available-clients>`.");
  lines.push(" - Throw on failure; job.ts maps that to exit code 1.");
  lines.push(" - Tests in `work.test.ts` cover happy path + at least one failure mode.");
  lines.push(" - Don't log payload bodies at info level — they may contain PII.");
  lines.push("</hybrid-skeleton>");
  return lines.join("\n");
}
