/**
 * Cron generator — hybrid.
 *
 * Emits two deterministic artifacts plus a focused bundle:
 *
 *   1. job.<ext> — entrypoint that calls work() with a hard timeout and
 *      surfaces failure as a non-zero exit so the scheduler retries
 *      or alerts. Per-language:
 *        - Node: AbortController + setTimeout
 *        - Python: signal.SIGALRM (Unix) or asyncio.wait_for(timeout)
 *        - Go: context.WithTimeout
 *   2. cronjob.yaml — Kubernetes CronJob manifest pinned to
 *      plan.schedule with activeDeadlineSeconds. The container command
 *      varies by language.
 *   3. Bundle (README + prompt + validate.sh) asking the LLM to write
 *      ONLY work.<ext> (one function: the job body).
 */

import { emitBundle } from "../bundle";
import { buildServiceUserPrompt, buildSystemPrompt, languageProfile } from "../prompt";
import type { ScaffoldLang } from "../../scaffold/concerns/types";
import type { Generator, GeneratedFile, GeneratorContext } from "../types";

export const cronLLMGenerator: Generator = {
  kind: "hybrid",

  supports(ctx) {
    return ctx.node.componentType === "cron";
  },

  async generate(ctx: GeneratorContext): Promise<GeneratedFile[]> {
    const lang = ctx.language ?? "node";
    const plan = ctx.node.plan ?? {};
    const schedule = plan.schedule || "0 0 * * *";
    const timeoutSeconds = parseTimeout(plan.timeout);

    const jobFile = `job.${languageProfile(lang).ext}`;
    const job = JOB_RENDERERS[lang](ctx, timeoutSeconds);
    const cronjob = renderCronJobYaml(ctx, schedule, timeoutSeconds, lang);
    const outputs = workOutputPaths(lang);
    const fence = lang === "node" ? "ts" : lang === "python" ? "python" : "go";
    const prompt = buildWorkPrompt(ctx, job, lang, jobFile, outputs, fence);

    const bundle = emitBundle(ctx, {
      systemPrompt: buildSystemPrompt(lang),
      userPrompt: prompt,
      expectedOutputs: outputs,
    });

    return [
      { path: jobFile, contents: job },
      { path: "cronjob.yaml", contents: cronjob },
      ...bundle,
    ];
  },
};

function workOutputPaths(lang: ScaffoldLang): string[] {
  switch (lang) {
    case "node":
      return ["work.ts", "work.test.ts"];
    case "python":
      return ["work.py", "test_work.py"];
    case "go":
      return ["work.go", "work_test.go"];
  }
}

function parseTimeout(raw: string | undefined): number {
  if (!raw) return 300;
  const m = raw.match(/(\d+)\s*([smh])?/i);
  if (!m) return 300;
  const n = parseInt(m[1], 10);
  const unit = (m[2] || "s").toLowerCase();
  return unit === "h" ? n * 3600 : unit === "m" ? n * 60 : n;
}

const JOB_RENDERERS: Record<ScaffoldLang, (ctx: GeneratorContext, timeoutSeconds: number) => string> = {
  node: renderJobTs,
  python: renderJobPython,
  go: renderJobGo,
};

function renderJobTs(ctx: GeneratorContext, timeoutSeconds: number): string {
  return [
    `// Scheduled job entrypoint for "${ctx.node.label}".`,
    `// Skeleton generated by Arkon buildout (deterministic).`,
    `// Business logic in work.ts is LLM-generated.`,
    ``,
    `import { work } from "./work";`,
    ``,
    `const TIMEOUT_MS = Number(process.env.JOB_TIMEOUT_MS ?? ${timeoutSeconds * 1000});`,
    ``,
    `/**`,
    ` * Runs work() under a hard timeout. The scheduler decides retry`,
    ` * policy; we only enforce per-invocation duration here.`,
    ` *`,
    ` * Exit codes:`,
    ` *   0  — success`,
    ` *   1  — work() threw`,
    ` *   2  — timeout fired`,
    ` */`,
    `async function run(): Promise<void> {`,
    `  const start = Date.now();`,
    `  const ac = new AbortController();`,
    `  const timeout = setTimeout(() => ac.abort(), TIMEOUT_MS);`,
    `  try {`,
    `    await work({ signal: ac.signal });`,
    `    console.log(\`job ok in \${Date.now() - start}ms\`);`,
    `  } catch (err) {`,
    `    if (ac.signal.aborted) {`,
    `      console.error(\`job timed out after \${TIMEOUT_MS}ms\`);`,
    `      process.exit(2);`,
    `    }`,
    `    console.error("job failed", err);`,
    `    process.exit(1);`,
    `  } finally {`,
    `    clearTimeout(timeout);`,
    `  }`,
    `}`,
    ``,
    `run();`,
    ``,
  ].join("\n");
}

function renderJobPython(ctx: GeneratorContext, timeoutSeconds: number): string {
  return [
    `"""Scheduled job entrypoint for "${ctx.node.label}".`,
    ``,
    `Skeleton generated by Arkon buildout (deterministic).`,
    `Business logic in work.py is LLM-generated.`,
    ``,
    `Exit codes:`,
    `  0  — success`,
    `  1  — work() raised`,
    `  2  — timeout fired`,
    `"""`,
    ``,
    `from __future__ import annotations`,
    ``,
    `import asyncio`,
    `import logging`,
    `import os`,
    `import sys`,
    `import time`,
    ``,
    `from work import work`,
    ``,
    `TIMEOUT_S = float(os.environ.get("JOB_TIMEOUT_S", "${timeoutSeconds}"))`,
    ``,
    `log = logging.getLogger("job")`,
    ``,
    `async def _run() -> None:`,
    `    start = time.monotonic()`,
    `    try:`,
    `        await asyncio.wait_for(work(), timeout=TIMEOUT_S)`,
    `    except asyncio.TimeoutError:`,
    `        log.error("job timed out after %.0fs", TIMEOUT_S)`,
    `        sys.exit(2)`,
    `    except Exception:`,
    `        log.exception("job failed")`,
    `        sys.exit(1)`,
    `    log.info("job ok in %.0fms", (time.monotonic() - start) * 1000)`,
    ``,
    `if __name__ == "__main__":`,
    `    logging.basicConfig(level=logging.INFO)`,
    `    asyncio.run(_run())`,
    ``,
  ].join("\n");
}

function renderJobGo(ctx: GeneratorContext, timeoutSeconds: number): string {
  return [
    `// Package main — scheduled job entrypoint for "${ctx.node.label}".`,
    `//`,
    `// Skeleton generated by Arkon buildout (deterministic).`,
    `// Business logic in work.go is LLM-generated.`,
    `//`,
    `// Exit codes:`,
    `//   0  — success`,
    `//   1  — Work() returned an error`,
    `//   2  — timeout fired (context cancelled)`,
    `package main`,
    ``,
    `import (`,
    `	"context"`,
    `	"errors"`,
    `	"log"`,
    `	"os"`,
    `	"strconv"`,
    `	"time"`,
    `)`,
    ``,
    `func main() {`,
    `	timeoutSeconds := ${timeoutSeconds}`,
    `	if v := os.Getenv("JOB_TIMEOUT_S"); v != "" {`,
    `		if n, err := strconv.Atoi(v); err == nil {`,
    `			timeoutSeconds = n`,
    `		}`,
    `	}`,
    `	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(timeoutSeconds)*time.Second)`,
    `	defer cancel()`,
    ``,
    `	start := time.Now()`,
    `	err := Work(ctx)`,
    `	if err != nil {`,
    `		if errors.Is(ctx.Err(), context.DeadlineExceeded) {`,
    `			log.Printf("job timed out after %ds", timeoutSeconds)`,
    `			os.Exit(2)`,
    `		}`,
    `		log.Printf("job failed: %v", err)`,
    `		os.Exit(1)`,
    `	}`,
    `	log.Printf("job ok in %dms", time.Since(start).Milliseconds())`,
    `}`,
    ``,
  ].join("\n");
}

function renderCronJobYaml(
  ctx: GeneratorContext,
  schedule: string,
  timeoutSeconds: number,
  lang: ScaffoldLang,
): string {
  const name = ctx.node.label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 52) || "cron-job";

  // Container command depends on language.
  const command =
    lang === "python"
      ? `["python", "job.py"]`
      : lang === "go"
        ? `["./job"]`
        : `["node", "job.js"]`;

  return [
    `# Kubernetes CronJob for "${ctx.node.label}".`,
    `# Schedule and timeout pulled from the canvas plan fields.`,
    `# Replace TODO image with your container image.`,
    `apiVersion: batch/v1`,
    `kind: CronJob`,
    `metadata:`,
    `  name: ${name}`,
    `spec:`,
    `  schedule: "${schedule}"`,
    `  concurrencyPolicy: Forbid`,
    `  successfulJobsHistoryLimit: 3`,
    `  failedJobsHistoryLimit: 3`,
    `  jobTemplate:`,
    `    spec:`,
    `      activeDeadlineSeconds: ${timeoutSeconds}`,
    `      backoffLimit: 1`,
    `      template:`,
    `        spec:`,
    `          restartPolicy: OnFailure`,
    `          containers:`,
    `            - name: job`,
    `              image: TODO-${name}:latest`,
    `              command: ${command}`,
    ``,
  ].join("\n");
}

function buildWorkPrompt(
  ctx: GeneratorContext,
  jobSrc: string,
  lang: ScaffoldLang,
  jobFile: string,
  outputs: string[],
  fenceLang: string,
): string {
  const [workFile, testFile] = outputs;
  const lines: string[] = [];
  lines.push(buildServiceUserPrompt(ctx));
  lines.push("");
  lines.push("<hybrid-skeleton>");
  lines.push(
    `The job entrypoint (\`${jobFile}\`) and the scheduler manifest ` +
      `(\`cronjob.yaml\`) are already generated. ${jobFile} runs ` +
      `\`work\` under a timeout and surfaces failure as a non-zero exit ` +
      `code. Your job is to write ONLY \`${workFile}\` (plus \`${testFile}\`) — ` +
      `do NOT regenerate ${jobFile} or cronjob.yaml.`,
  );
  lines.push("");
  lines.push(`Here is the \`${jobFile}\` you must match:`);
  lines.push("```" + fenceLang);
  lines.push(jobSrc.trimEnd());
  lines.push("```");
  lines.push("");
  lines.push(`Implement in \`${workFile}\`:`);
  lines.push(...workFnRules(lang, workFile, testFile, jobFile));
  lines.push("</hybrid-skeleton>");
  return lines.join("\n");
}

function workFnRules(
  lang: ScaffoldLang,
  workFile: string,
  testFile: string,
  jobFile: string,
): string[] {
  const common = [
    " - Idempotent: a retry on the same schedule window must not double-process.",
    " - Use ONLY the clients listed in `<available-clients>`.",
    ` - Tests in \`${testFile}\` cover happy path + at least one failure mode.`,
    " - Don't log payload bodies at info level — they may contain PII.",
  ];
  switch (lang) {
    case "node":
      return [
        " - `export async function work(opts: { signal: AbortSignal }): Promise<void>`",
        " - Honor opts.signal — long-running fetches/queries should pass it through.",
        ` - Throw on failure; ${jobFile} maps that to exit code 1.`,
        ...common,
      ];
    case "python":
      return [
        " - `async def work() -> None`",
        ` - Honor asyncio cancellation — long-running awaits should be cancellable. ${jobFile}`,
        `   wraps your work in asyncio.wait_for(timeout), which raises CancelledError.`,
        ` - Raise on failure; ${jobFile} maps that to exit code 1.`,
        ...common,
      ];
    case "go":
      return [
        " - `func Work(ctx context.Context) error` (exported).",
        ` - Honor ctx.Done() — long-running calls should accept ctx (HTTP client, DB, etc.). ${jobFile}`,
        `   passes a context with timeout; respect it.`,
        ` - Return non-nil error on failure; ${jobFile} maps that to exit code 1.`,
        ...common,
      ];
  }
}
