/**
 * Serverless generator — hybrid.
 *
 * Inspects `plan.trigger` (free-form text in the canvas) to pick one of
 * four event shapes — HTTP (API Gateway v2), S3, SQS, or schedule
 * (EventBridge) — and emits a `handler.ts` skeleton that parses that
 * exact event shape, calls a focused per-event business-logic
 * function (LLM-filled), and returns the right response shape.
 *
 * Why hybrid: the event shapes are well-known AWS Lambda contracts.
 * Hand-rolling Records iteration, body parsing, and response shaping
 * is mechanical and easy to get subtly wrong. Baking it into the
 * skeleton means the LLM only writes the business logic — typically
 * 10-30 lines per Lambda.
 *
 * Bundle output (LLM-filled):
 *   - HTTP   → process.ts:  async (input: HttpInput) => HttpOutput
 *   - S3     → process.ts:  async (record: S3Record) => void
 *   - SQS    → process.ts:  async (message: SqsMessage) => void
 *   - sched  → process.ts:  async (event: ScheduleEvent) => void
 *
 * Falls back to today's single-bundle behavior for non-Node languages.
 */

import { emitBundle } from "../bundle";
import { buildServiceUserPrompt, buildSystemPrompt } from "../prompt";
import type { Generator, GeneratedFile, GeneratorContext } from "../types";

type Trigger = "http" | "s3" | "sqs" | "schedule";

const FALLBACK_GUIDANCE = [
  "",
  "<serverless>",
  "This is a serverless function — single entry, no HTTP server boilerplate.",
  "The handler receives an event object whose shape depends on the trigger:",
  " - HTTP: { method, path, headers, query, body }",
  " - S3: { Records: [{ s3: { bucket: { name }, object: { key } } }] }",
  " - SQS / message-queue: { Records: [{ body, messageAttributes }] }",
  " - Schedule / cron: { time, name } (CloudWatch Event shape)",
  "Emit exactly one handler file (export-named or default per language convention) plus its tests.",
  "</serverless>",
].join("\n");

export const serverlessLLMGenerator: Generator = {
  kind: "hybrid",

  supports(ctx) {
    return ctx.node.componentType === "serverless";
  },

  async generate(ctx: GeneratorContext): Promise<GeneratedFile[]> {
    const lang = ctx.language ?? "node";

    if (lang !== "node") {
      return emitBundle(ctx, {
        systemPrompt: buildSystemPrompt(lang),
        userPrompt: buildServiceUserPrompt(ctx) + FALLBACK_GUIDANCE,
      });
    }

    const trigger = detectTrigger(ctx.node.plan?.trigger);
    const handler = renderHandler(ctx, trigger);
    const prompt = buildHandlerPrompt(ctx, trigger, handler);
    const bundle = emitBundle(ctx, {
      systemPrompt: buildSystemPrompt("node"),
      userPrompt: prompt,
      expectedOutputs: ["process.ts", "process.test.ts"],
    });
    return [{ path: "handler.ts", contents: handler }, ...bundle];
  },
};

/**
 * Best-effort substring match on the plan.trigger free-form text.
 * Order matters — "S3 event" should pick s3 before any false positive
 * on a path-like word.
 */
function detectTrigger(raw: string | undefined): Trigger {
  const t = (raw ?? "").toLowerCase();
  if (/s3/.test(t)) return "s3";
  if (/sqs|kafka|kinesis|message|queue/.test(t)) return "sqs";
  if (/schedul|cron|eventbridge|rate\s*\(|cron\s*\(/.test(t)) return "schedule";
  // Default to HTTP — most serverless functions are API-fronted.
  return "http";
}

function renderHandler(ctx: GeneratorContext, trigger: Trigger): string {
  switch (trigger) {
    case "http":
      return renderHttpHandler(ctx);
    case "s3":
      return renderS3Handler(ctx);
    case "sqs":
      return renderSqsHandler(ctx);
    case "schedule":
      return renderScheduleHandler(ctx);
  }
}

function renderHttpHandler(ctx: GeneratorContext): string {
  return [
    `// Serverless HTTP handler for "${ctx.node.label}".`,
    `// Skeleton generated by Arkon buildout (deterministic).`,
    `// Business logic in process.ts is LLM-generated.`,
    ``,
    `import { process as processInput, type HttpInput, type HttpOutput } from "./process";`,
    ``,
    `/** API Gateway v2 (HTTP API) event shape. */`,
    `interface ApiGatewayV2Event {`,
    `  version: "2.0";`,
    `  routeKey: string;`,
    `  rawPath: string;`,
    `  rawQueryString: string;`,
    `  headers: Record<string, string>;`,
    `  queryStringParameters?: Record<string, string>;`,
    `  body?: string;`,
    `  isBase64Encoded: boolean;`,
    `  requestContext: { http: { method: string; path: string } };`,
    `}`,
    ``,
    `interface ApiGatewayV2Result {`,
    `  statusCode: number;`,
    `  headers?: Record<string, string>;`,
    `  body?: string;`,
    `}`,
    ``,
    `function parseBody(event: ApiGatewayV2Event): unknown {`,
    `  if (!event.body) return undefined;`,
    `  const raw = event.isBase64Encoded`,
    `    ? Buffer.from(event.body, "base64").toString("utf8")`,
    `    : event.body;`,
    `  const ct = (event.headers["content-type"] ?? event.headers["Content-Type"] ?? "").toLowerCase();`,
    `  if (ct.includes("application/json")) {`,
    `    try { return JSON.parse(raw); } catch { return undefined; }`,
    `  }`,
    `  return raw;`,
    `}`,
    ``,
    `export async function handler(event: ApiGatewayV2Event): Promise<ApiGatewayV2Result> {`,
    `  const input: HttpInput = {`,
    `    method: event.requestContext.http.method,`,
    `    path: event.requestContext.http.path,`,
    `    query: event.queryStringParameters ?? {},`,
    `    headers: event.headers,`,
    `    body: parseBody(event),`,
    `  };`,
    `  try {`,
    `    const result = await processInput(input);`,
    `    return {`,
    `      statusCode: result.status,`,
    `      headers: { "content-type": "application/json", ...(result.headers ?? {}) },`,
    `      body: result.body === undefined ? undefined : JSON.stringify(result.body),`,
    `    };`,
    `  } catch (err) {`,
    `    console.error("handler error", err);`,
    `    return {`,
    `      statusCode: 500,`,
    `      headers: { "content-type": "application/json" },`,
    `      body: JSON.stringify({ error: "internal_error" }),`,
    `    };`,
    `  }`,
    `}`,
    ``,
  ].join("\n");
}

function renderS3Handler(ctx: GeneratorContext): string {
  return [
    `// Serverless S3 handler for "${ctx.node.label}".`,
    `// Skeleton generated by Arkon buildout (deterministic).`,
    `// Business logic in process.ts is LLM-generated.`,
    ``,
    `import { process as processRecord, type S3Record } from "./process";`,
    ``,
    `interface S3Event {`,
    `  Records: Array<{`,
    `    eventSource: "aws:s3";`,
    `    eventName: string;`,
    `    s3: {`,
    `      bucket: { name: string; arn: string };`,
    `      object: { key: string; size: number; eTag: string };`,
    `    };`,
    `  }>;`,
    `}`,
    ``,
    `interface BatchItemFailure { itemIdentifier: string }`,
    `interface BatchResponse { batchItemFailures: BatchItemFailure[] }`,
    ``,
    `/**`,
    ` * Iterates the records, calls per-record business logic, and reports`,
    ` * partial failures via the batchItemFailures contract so the failing`,
    ` * records are retried (Lambda S3 event source supports this when`,
    ` * configured with a destination).`,
    ` */`,
    `export async function handler(event: S3Event): Promise<BatchResponse> {`,
    `  const failures: BatchItemFailure[] = [];`,
    `  for (const r of event.Records) {`,
    `    const record: S3Record = {`,
    `      bucket: r.s3.bucket.name,`,
    `      key: decodeURIComponent(r.s3.object.key.replace(/\\+/g, " ")),`,
    `      size: r.s3.object.size,`,
    `      etag: r.s3.object.eTag,`,
    `      eventName: r.eventName,`,
    `    };`,
    `    try {`,
    `      await processRecord(record);`,
    `    } catch (err) {`,
    `      console.error("s3 record failed", { key: record.key, err });`,
    `      failures.push({ itemIdentifier: \`\${record.bucket}/\${record.key}\` });`,
    `    }`,
    `  }`,
    `  return { batchItemFailures: failures };`,
    `}`,
    ``,
  ].join("\n");
}

function renderSqsHandler(ctx: GeneratorContext): string {
  return [
    `// Serverless SQS handler for "${ctx.node.label}".`,
    `// Skeleton generated by Arkon buildout (deterministic).`,
    `// Business logic in process.ts is LLM-generated.`,
    ``,
    `import { process as processMessage, type SqsMessage } from "./process";`,
    ``,
    `interface SqsEvent {`,
    `  Records: Array<{`,
    `    messageId: string;`,
    `    body: string;`,
    `    attributes: Record<string, string>;`,
    `    messageAttributes: Record<string, { stringValue?: string; dataType: string }>;`,
    `    eventSource: "aws:sqs";`,
    `  }>;`,
    `}`,
    ``,
    `interface BatchItemFailure { itemIdentifier: string }`,
    `interface BatchResponse { batchItemFailures: BatchItemFailure[] }`,
    ``,
    `function parseBody(raw: string): unknown {`,
    `  try { return JSON.parse(raw); } catch { return raw; }`,
    `}`,
    ``,
    `/**`,
    ` * Per-message dispatch. Failed messages report itemIdentifier so SQS`,
    ` * retries only those — the rest are deleted as successful. Lambda`,
    ` * must be configured with ReportBatchItemFailures for this to take`,
    ` * effect; otherwise a throw fails the whole batch.`,
    ` */`,
    `export async function handler(event: SqsEvent): Promise<BatchResponse> {`,
    `  const failures: BatchItemFailure[] = [];`,
    `  for (const r of event.Records) {`,
    `    const message: SqsMessage = {`,
    `      id: r.messageId,`,
    `      body: parseBody(r.body),`,
    `      attributes: Object.fromEntries(`,
    `        Object.entries(r.messageAttributes).map(([k, v]) => [k, v.stringValue ?? ""]),`,
    `      ),`,
    `    };`,
    `    try {`,
    `      await processMessage(message);`,
    `    } catch (err) {`,
    `      console.error("sqs message failed", { id: message.id, err });`,
    `      failures.push({ itemIdentifier: message.id });`,
    `    }`,
    `  }`,
    `  return { batchItemFailures: failures };`,
    `}`,
    ``,
  ].join("\n");
}

function renderScheduleHandler(ctx: GeneratorContext): string {
  return [
    `// Serverless scheduled handler for "${ctx.node.label}".`,
    `// Skeleton generated by Arkon buildout (deterministic).`,
    `// Business logic in process.ts is LLM-generated.`,
    ``,
    `import { process as processTick, type ScheduleEvent } from "./process";`,
    ``,
    `/** EventBridge scheduled event shape. */`,
    `interface EventBridgeEvent {`,
    `  version: string;`,
    `  id: string;`,
    `  "detail-type": "Scheduled Event";`,
    `  source: "aws.events";`,
    `  account: string;`,
    `  time: string;`,
    `  region: string;`,
    `  resources: string[];`,
    `  detail: Record<string, unknown>;`,
    `}`,
    ``,
    `export async function handler(event: EventBridgeEvent): Promise<void> {`,
    `  const tick: ScheduleEvent = {`,
    `    firedAt: new Date(event.time),`,
    `    rule: event.resources[0] ?? "",`,
    `  };`,
    `  // The scheduler retries on throw (per the destination config). We`,
    `  // let exceptions propagate so EventBridge can surface them.`,
    `  await processTick(tick);`,
    `}`,
    ``,
  ].join("\n");
}

function buildHandlerPrompt(ctx: GeneratorContext, trigger: Trigger, handlerSrc: string): string {
  const lines: string[] = [];
  lines.push(buildServiceUserPrompt(ctx));
  lines.push("");
  lines.push("<hybrid-skeleton>");
  lines.push(
    `Trigger detected: **${trigger}**. The Lambda entrypoint (\`handler.ts\`) is ` +
      `already generated. It parses the AWS event shape, dispatches to a ` +
      `focused per-event function in \`process.ts\`, and handles errors / ` +
      `partial-batch failures. Your job is to write ONLY \`process.ts\` (plus ` +
      `\`process.test.ts\`) — do NOT regenerate \`handler.ts\`.`,
  );
  lines.push("");
  lines.push("Here is the `handler.ts` you must match:");
  lines.push("```ts");
  lines.push(handlerSrc.trimEnd());
  lines.push("```");
  lines.push("");
  lines.push("Implement in `process.ts`:");
  lines.push(...processFnHint(trigger));
  lines.push(" - Validate input at the boundary. Throw on schema mismatch.");
  lines.push(" - Use ONLY the clients listed in `<available-clients>`.");
  lines.push(" - Tests in `process.test.ts` cover happy + at least one failure mode.");
  lines.push(" - Don't log payload bodies at info level — they may contain PII.");
  lines.push("</hybrid-skeleton>");
  return lines.join("\n");
}

function processFnHint(trigger: Trigger): string[] {
  switch (trigger) {
    case "http":
      return [
        " - Export `type HttpInput = { method, path, query, headers, body }`.",
        " - Export `type HttpOutput = { status: number; body?: unknown; headers?: Record<string,string> }`.",
        " - Export `export async function process(input: HttpInput): Promise<HttpOutput>`.",
      ];
    case "s3":
      return [
        " - Export `type S3Record = { bucket, key, size, etag, eventName }`.",
        " - Export `export async function process(record: S3Record): Promise<void>`.",
        " - The handler iterates records — keep this function focused on one record.",
      ];
    case "sqs":
      return [
        " - Export `type SqsMessage = { id, body, attributes }`.",
        " - Export `export async function process(message: SqsMessage): Promise<void>`.",
        " - The handler iterates messages — keep this function focused on one message.",
      ];
    case "schedule":
      return [
        " - Export `type ScheduleEvent = { firedAt: Date; rule: string }`.",
        " - Export `export async function process(tick: ScheduleEvent): Promise<void>`.",
        " - Idempotent: a retry on the same firedAt should not double-process.",
      ];
  }
}
