/**
 * Service generator — hybrid.
 *
 * Two modes, selected by whether `node.endpoints` is non-empty:
 *
 * ## Hybrid mode (endpoints declared)
 * Emits TWO artifacts:
 *  1. `server.<ext>` — DETERMINISTIC HTTP server skeleton. Registers a
 *     route per declared endpoint, wires error handling, and dispatches
 *     to a named handler imported from `handlers.<ext>`.
 *  2. A bundle (`README.md` + `prompt.md` + `validate.sh`) that asks
 *     the LLM to produce `handlers.<ext>` exporting one focused
 *     function per endpoint. The prompt embeds the server source so
 *     the LLM matches signatures exactly.
 *
 * Why the split: route registration, parameter parsing, content-type
 * negotiation, and error → status-code mapping are mechanical given a
 * structured endpoint list. The actual business logic per endpoint is
 * the only piece that needs prose understanding — focused enough to
 * prompt for individually.
 *
 * ## Bundle-only fallback (no endpoints)
 * Backward-compatible. Services without declared endpoints still get
 * the single bundle from before — the LLM owns the whole shape.
 *
 * v1 scope: Node/TS skeleton only. Python/Go follow the same pattern;
 * adding them is mechanical (mirrors what stream-llm.ts does).
 */

import { emitBundle } from "../bundle";
import { buildServiceUserPrompt, buildSystemPrompt } from "../prompt";
import type { Endpoint } from "../../../types";
import type { Generator, GeneratedFile, GeneratorContext } from "../types";

export const serviceLLMGenerator: Generator = {
  kind: "hybrid",

  supports(ctx) {
    return ctx.node.componentType === "service";
  },

  async generate(ctx: GeneratorContext): Promise<GeneratedFile[]> {
    const lang = ctx.language ?? "node";
    const endpoints = ctx.endpoints ?? ctx.node.endpoints ?? [];

    // Today's hybrid skeleton is TS-only. Python/Go endpoints fall back
    // to the bundle prompt — same as how stream-processor handled it
    // before extending to Python+Go.
    const supportsHybrid = lang === "node";

    if (endpoints.length === 0 || !supportsHybrid) {
      return emitBundle(ctx, {
        systemPrompt: buildSystemPrompt(lang),
        userPrompt: buildServiceUserPrompt(ctx),
      });
    }

    return emitHybrid(ctx, endpoints);
  },
};

function emitHybrid(ctx: GeneratorContext, endpoints: Endpoint[]): GeneratedFile[] {
  const handlers = endpoints.map((ep, idx) => ({
    endpoint: ep,
    idx,
    name: handlerFnName(ep, idx),
  }));

  const server = renderServerTs(ctx, handlers);
  const operatorPrompt = buildHandlerPrompt(ctx, handlers, server);
  const bundle = emitBundle(ctx, {
    systemPrompt: buildSystemPrompt("node"),
    userPrompt: operatorPrompt,
    expectedOutputs: ["handlers.ts", "handlers.test.ts"],
  });

  return [{ path: "server.ts", contents: server }, ...bundle];
}

interface HandlerRef {
  endpoint: Endpoint;
  idx: number;
  name: string;
}

function handlerFnName(ep: Endpoint, idx: number): string {
  const slug = ep.path
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 40);
  return `${ep.method.toLowerCase()}_${String(idx + 1).padStart(2, "0")}${slug ? `_${slug}` : ""}`;
}

/**
 * Render server.ts using the built-in `node:http` module so the
 * skeleton runs without any extra dependency. The scaffold subsystem
 * already chose a framework for the running server; this generator is
 * about the BUILDOUT artifact, which prioritizes self-contained code
 * that compiles and runs against any project shape.
 */
function renderServerTs(ctx: GeneratorContext, handlers: HandlerRef[]): string {
  const lines: string[] = [];
  const importNames = handlers.map((h) => h.name).join(", ");

  lines.push(`// HTTP server for "${ctx.node.label}".`);
  lines.push(`// Skeleton generated by Arkon buildout (deterministic).`);
  lines.push(`// Handler function bodies are LLM-generated — see handlers.ts.`);
  lines.push(``);
  lines.push(`import { createServer, type IncomingMessage, type ServerResponse } from "node:http";`);
  if (handlers.length > 0) {
    lines.push(`import { ${importNames} } from "./handlers";`);
  }
  lines.push(``);
  lines.push(`export interface RouteCtx {`);
  lines.push(`  method: string;`);
  lines.push(`  path: string;`);
  lines.push(`  query: Record<string, string>;`);
  lines.push(`  headers: Record<string, string | string[] | undefined>;`);
  lines.push(`  body: unknown;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export interface RouteResult {`);
  lines.push(`  status: number;`);
  lines.push(`  body?: unknown;`);
  lines.push(`  headers?: Record<string, string>;`);
  lines.push(`}`);
  lines.push(``);

  // Path → method → handler map. The skeleton resolves the path with a
  // straightforward switch since route trees aren't worth the
  // complexity until the user upgrades the framework.
  lines.push(`async function dispatch(rc: RouteCtx): Promise<RouteResult> {`);
  lines.push(`  switch (\`\${rc.method} \${rc.path}\`) {`);
  for (const h of handlers) {
    const route = `${h.endpoint.method.toUpperCase()} ${h.endpoint.path}`;
    lines.push(`    case ${JSON.stringify(route)}:`);
    lines.push(`      return ${h.name}(rc);`);
  }
  lines.push(`    default:`);
  lines.push(`      return { status: 404, body: { error: "not_found", path: rc.path } };`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`async function readBody(req: IncomingMessage): Promise<unknown> {`);
  lines.push(`  const chunks: Buffer[] = [];`);
  lines.push(`  for await (const chunk of req) chunks.push(chunk as Buffer);`);
  lines.push(`  if (chunks.length === 0) return undefined;`);
  lines.push(`  const raw = Buffer.concat(chunks).toString("utf8");`);
  lines.push(`  const ct = (req.headers["content-type"] ?? "").toLowerCase();`);
  lines.push(`  if (ct.includes("application/json")) {`);
  lines.push(`    try { return JSON.parse(raw); } catch { return undefined; }`);
  lines.push(`  }`);
  lines.push(`  return raw;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`function parseQuery(url: string): { path: string; query: Record<string, string> } {`);
  lines.push(`  const [path, qs = ""] = url.split("?");`);
  lines.push(`  const query: Record<string, string> = {};`);
  lines.push(`  for (const p of qs.split("&").filter(Boolean)) {`);
  lines.push(`    const [k, v = ""] = p.split("=");`);
  lines.push(`    query[decodeURIComponent(k)] = decodeURIComponent(v);`);
  lines.push(`  }`);
  lines.push(`  return { path, query };`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`async function handle(req: IncomingMessage, res: ServerResponse): Promise<void> {`);
  lines.push(`  const { path, query } = parseQuery(req.url ?? "/");`);
  lines.push(`  const rc: RouteCtx = {`);
  lines.push(`    method: req.method ?? "GET",`);
  lines.push(`    path,`);
  lines.push(`    query,`);
  lines.push(`    headers: req.headers,`);
  lines.push(`    body: await readBody(req),`);
  lines.push(`  };`);
  lines.push(`  try {`);
  lines.push(`    const result = await dispatch(rc);`);
  lines.push(`    res.statusCode = result.status;`);
  lines.push(`    for (const [k, v] of Object.entries(result.headers ?? {})) res.setHeader(k, v);`);
  lines.push(`    if (result.body !== undefined) {`);
  lines.push(`      res.setHeader("content-type", "application/json");`);
  lines.push(`      res.end(JSON.stringify(result.body));`);
  lines.push(`    } else {`);
  lines.push(`      res.end();`);
  lines.push(`    }`);
  lines.push(`  } catch (err) {`);
  lines.push(`    res.statusCode = 500;`);
  lines.push(`    res.setHeader("content-type", "application/json");`);
  lines.push(`    res.end(JSON.stringify({ error: "internal_error", message: (err as Error).message }));`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export function startServer(port = Number(process.env.PORT ?? 8080)): void {`);
  lines.push(`  const server = createServer((req, res) => { void handle(req, res); });`);
  lines.push(`  server.listen(port, () => console.log(\`listening on :\${port}\`));`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`if (import.meta.url === \`file://\${process.argv[1]}\`) startServer();`);
  return lines.join("\n") + "\n";
}

function buildHandlerPrompt(
  ctx: GeneratorContext,
  handlers: HandlerRef[],
  serverSrc: string,
): string {
  const lines: string[] = [];
  lines.push(buildServiceUserPrompt(ctx));
  lines.push("");
  lines.push("<hybrid-skeleton>");
  lines.push(
    "The HTTP server skeleton (`server.ts`) is already generated. It " +
      "registers a route per declared endpoint, parses query/body, and " +
      "dispatches to a named handler in `handlers.ts`. Your job is to " +
      "write ONLY `handlers.ts` (plus `handlers.test.ts`) — do NOT " +
      "regenerate `server.ts`.",
  );
  lines.push("");
  lines.push("Here is the `server.ts` you must match:");
  lines.push("```ts");
  lines.push(serverSrc.trimEnd());
  lines.push("```");
  lines.push("");
  lines.push("Handlers to implement in `handlers.ts`:");
  for (const h of handlers) {
    const codes = h.endpoint.responseCodes?.length
      ? ` responses=[${h.endpoint.responseCodes.join(",")}]`
      : "";
    const qp = h.endpoint.queryParams?.length
      ? ` query=[${h.endpoint.queryParams.map((q) => q.name + (q.required ? "" : "?")).join(",")}]`
      : "";
    lines.push(
      `- \`${h.name}\` — ${h.endpoint.method.toUpperCase()} ${h.endpoint.path}${qp}${codes}`,
    );
  }
  lines.push("");
  lines.push("Rules:");
  lines.push(" - Each handler is `async (rc: RouteCtx): Promise<RouteResult>`. Match the types from server.ts.");
  lines.push(" - Validate request input at the boundary; return 4xx with a structured error body on failure.");
  lines.push(" - Use ONLY the clients listed in `<available-clients>`. Do not invent new dependencies.");
  lines.push(" - Tests in `handlers.test.ts` cover at least one happy path and one error path per handler.");
  lines.push(" - Don't log request bodies at info level — they may contain PII.");
  lines.push("</hybrid-skeleton>");
  return lines.join("\n");
}
