/**
 * Webhook generator — hybrid.
 *
 * Inbound (outbound edges present): emits an HMAC-verifying receiver
 * skeleton. Bundle asks LLM to write `process(payload)` only.
 *
 * Outbound (inbound edges only): emits a signed emitter skeleton with
 * idempotency keys, retry + exponential backoff, timeout. Bundle asks
 * LLM to write `buildPayload(input)` only.
 *
 * Why bother making this hybrid: HMAC verification and retry/backoff
 * are exactly the kind of mechanical, security-critical code we don't
 * want an LLM inventing. A custom HMAC compare without timing-safe
 * equality is a real bug we'd never want shipped; baking it into the
 * skeleton makes it impossible to forget.
 *
 * v1 scope: TS only. Python+Go follow the same pattern; tracked TODO.
 */

import { emitBundle } from "../bundle";
import { buildServiceUserPrompt, buildSystemPrompt, languageProfile } from "../prompt";
import type { ScaffoldLang } from "../../scaffold/concerns/types";
import type { Generator, GeneratedFile, GeneratorContext } from "../types";

function isInboundWebhook(ctx: GeneratorContext): boolean {
  return ctx.outbound.length > 0;
}

// (Fallback guidance constants removed — every language now has a
//  hybrid skeleton, so the fallback prompt path is dead code.)

export const webhookLLMGenerator: Generator = {
  kind: "hybrid",

  supports(ctx) {
    return ctx.node.componentType === "webhook";
  },

  async generate(ctx: GeneratorContext): Promise<GeneratedFile[]> {
    const lang = ctx.language ?? "node";
    return isInboundWebhook(ctx) ? emitInbound(ctx, lang) : emitOutbound(ctx, lang);
  },
};

function langExt(lang: ScaffoldLang): string {
  return languageProfile(lang).ext;
}

function fenceLang(lang: ScaffoldLang): string {
  return lang === "node" ? "ts" : lang === "python" ? "python" : "go";
}

function inboundOutputPaths(lang: ScaffoldLang): string[] {
  switch (lang) {
    case "node":
      return ["process.ts", "process.test.ts"];
    case "python":
      return ["process.py", "test_process.py"];
    case "go":
      return ["process.go", "process_test.go"];
  }
}

function outboundOutputPaths(lang: ScaffoldLang): string[] {
  switch (lang) {
    case "node":
      return ["payload.ts", "payload.test.ts"];
    case "python":
      return ["payload.py", "test_payload.py"];
    case "go":
      return ["payload.go", "payload_test.go"];
  }
}

function emitInbound(ctx: GeneratorContext, lang: ScaffoldLang): GeneratedFile[] {
  const receiver = INBOUND_RENDERERS[lang](ctx);
  const outputs = inboundOutputPaths(lang);
  const receiverFile = `receiver.${langExt(lang)}`;
  const prompt = buildInboundPrompt(ctx, receiver, lang, receiverFile, outputs);
  const bundle = emitBundle(ctx, {
    systemPrompt: buildSystemPrompt(lang),
    userPrompt: prompt,
    expectedOutputs: outputs,
  });
  return [{ path: receiverFile, contents: receiver }, ...bundle];
}

function emitOutbound(ctx: GeneratorContext, lang: ScaffoldLang): GeneratedFile[] {
  const emitter = OUTBOUND_RENDERERS[lang](ctx);
  const outputs = outboundOutputPaths(lang);
  const emitterFile = `emitter.${langExt(lang)}`;
  const prompt = buildOutboundPrompt(ctx, emitter, lang, emitterFile, outputs);
  const bundle = emitBundle(ctx, {
    systemPrompt: buildSystemPrompt(lang),
    userPrompt: prompt,
    expectedOutputs: outputs,
  });
  return [{ path: emitterFile, contents: emitter }, ...bundle];
}

const INBOUND_RENDERERS: Record<ScaffoldLang, (ctx: GeneratorContext) => string> = {
  node: renderInboundReceiver,
  python: renderInboundReceiverPython,
  go: renderInboundReceiverGo,
};

const OUTBOUND_RENDERERS: Record<ScaffoldLang, (ctx: GeneratorContext) => string> = {
  node: renderOutboundEmitter,
  python: renderOutboundEmitterPython,
  go: renderOutboundEmitterGo,
};

function renderInboundReceiver(ctx: GeneratorContext): string {
  const plan = ctx.node.plan ?? {};
  const method = (plan.method || "POST").toUpperCase();
  const downstream = ctx.outbound.map((e) => `${e.otherNodeLabel} (${e.otherComponentType})`);

  const lines: string[] = [];
  lines.push(`// HMAC-verifying webhook receiver for "${ctx.node.label}".`);
  lines.push(`// Skeleton generated by Arkon buildout (deterministic).`);
  lines.push(`// Business logic in process.ts is LLM-generated.`);
  lines.push(``);
  if (downstream.length > 0) {
    lines.push(`// Downstream dispatch targets:`);
    for (const d of downstream) lines.push(`//   - ${d}`);
    lines.push(``);
  }
  lines.push(`import { createHmac, timingSafeEqual } from "node:crypto";`);
  lines.push(`import type { IncomingMessage, ServerResponse } from "node:http";`);
  lines.push(`import { process as processPayload } from "./process";`);
  lines.push(``);
  lines.push(`/** Env-configured secret. We read once at module load to fail fast. */`);
  lines.push(`const WEBHOOK_SECRET = (() => {`);
  lines.push(`  const s = process.env.WEBHOOK_SECRET;`);
  lines.push(`  if (!s) throw new Error("WEBHOOK_SECRET env var is required");`);
  lines.push(`  return s;`);
  lines.push(`})();`);
  lines.push(``);
  lines.push(`/** Signature header name. Override per third-party convention. */`);
  lines.push(`const SIGNATURE_HEADER = process.env.WEBHOOK_SIGNATURE_HEADER ?? "x-signature";`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Verify the HMAC-SHA256 signature using timing-safe comparison.`);
  lines.push(` * Returns true on match, false otherwise (including malformed input).`);
  lines.push(` */`);
  lines.push(`export function verifySignature(rawBody: string, signature: string | undefined): boolean {`);
  lines.push(`  if (!signature) return false;`);
  lines.push(`  const expected = createHmac("sha256", WEBHOOK_SECRET).update(rawBody).digest("hex");`);
  lines.push(`  // Strip optional "sha256=" prefix used by some providers (e.g. GitHub).`);
  lines.push(`  const provided = signature.startsWith("sha256=") ? signature.slice(7) : signature;`);
  lines.push(`  if (provided.length !== expected.length) return false;`);
  lines.push(`  try {`);
  lines.push(`    return timingSafeEqual(Buffer.from(expected, "hex"), Buffer.from(provided, "hex"));`);
  lines.push(`  } catch {`);
  lines.push(`    return false;`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Generic HTTP handler. Adapt to your framework (Express, Fastify, etc.)`);
  lines.push(` * by passing the IncomingMessage / ServerResponse pair in. Returns void;`);
  lines.push(` * the response is written directly.`);
  lines.push(` */`);
  lines.push(`export async function handle(req: IncomingMessage, res: ServerResponse): Promise<void> {`);
  lines.push(`  if (req.method !== ${JSON.stringify(method)}) {`);
  lines.push(`    res.statusCode = 405;`);
  lines.push(`    res.end();`);
  lines.push(`    return;`);
  lines.push(`  }`);
  lines.push(`  const chunks: Buffer[] = [];`);
  lines.push(`  for await (const c of req) chunks.push(c as Buffer);`);
  lines.push(`  const rawBody = Buffer.concat(chunks).toString("utf8");`);
  lines.push(``);
  lines.push(`  const sigHeader = req.headers[SIGNATURE_HEADER];`);
  lines.push(`  const signature = Array.isArray(sigHeader) ? sigHeader[0] : sigHeader;`);
  lines.push(`  if (!verifySignature(rawBody, signature)) {`);
  lines.push(`    res.statusCode = 401;`);
  lines.push(`    res.end(JSON.stringify({ error: "invalid_signature" }));`);
  lines.push(`    return;`);
  lines.push(`  }`);
  lines.push(``);
  lines.push(`  let payload: unknown;`);
  lines.push(`  try {`);
  lines.push(`    payload = JSON.parse(rawBody);`);
  lines.push(`  } catch {`);
  lines.push(`    res.statusCode = 400;`);
  lines.push(`    res.end(JSON.stringify({ error: "invalid_json" }));`);
  lines.push(`    return;`);
  lines.push(`  }`);
  lines.push(``);
  lines.push(`  try {`);
  lines.push(`    // process() is the LLM-filled business logic. It owns schema`);
  lines.push(`    // validation and downstream dispatch.`);
  lines.push(`    await processPayload(payload);`);
  lines.push(`    res.statusCode = 200;`);
  lines.push(`    res.end();`);
  lines.push(`  } catch (err) {`);
  lines.push(`    // Don't echo internal error detail back to the caller — that's`);
  lines.push(`    // an enumeration vector. Log full detail server-side instead.`);
  lines.push(`    console.error("webhook process failed", err);`);
  lines.push(`    res.statusCode = 500;`);
  lines.push(`    res.end(JSON.stringify({ error: "internal_error" }));`);
  lines.push(`  }`);
  lines.push(`}`);
  return lines.join("\n") + "\n";
}

function renderOutboundEmitter(ctx: GeneratorContext): string {
  const plan = ctx.node.plan ?? {};
  const url = plan.url || "https://example.com/webhook";
  const method = (plan.method || "POST").toUpperCase();

  const lines: string[] = [];
  lines.push(`// Signed-and-retrying webhook emitter for "${ctx.node.label}".`);
  lines.push(`// Skeleton generated by Arkon buildout (deterministic).`);
  lines.push(`// Payload mapping in payload.ts is LLM-generated.`);
  lines.push(``);
  lines.push(`import { createHmac, randomUUID } from "node:crypto";`);
  lines.push(`import { buildPayload } from "./payload";`);
  lines.push(``);
  lines.push(`/** Plan-defaults; override via env. */`);
  lines.push(`const WEBHOOK_URL = process.env.WEBHOOK_URL ?? ${JSON.stringify(url)};`);
  lines.push(`const WEBHOOK_SECRET = (() => {`);
  lines.push(`  const s = process.env.WEBHOOK_SECRET;`);
  lines.push(`  if (!s) throw new Error("WEBHOOK_SECRET env var is required");`);
  lines.push(`  return s;`);
  lines.push(`})();`);
  lines.push(``);
  lines.push(`const TIMEOUT_MS = Number(process.env.WEBHOOK_TIMEOUT_MS ?? 5000);`);
  lines.push(`const MAX_ATTEMPTS = Number(process.env.WEBHOOK_MAX_ATTEMPTS ?? 3);`);
  lines.push(``);
  lines.push(`function sign(body: string): string {`);
  lines.push(`  return createHmac("sha256", WEBHOOK_SECRET).update(body).digest("hex");`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`async function sleep(ms: number): Promise<void> {`);
  lines.push(`  return new Promise((resolve) => setTimeout(resolve, ms));`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Emit one event. Computes the payload via the LLM-filled mapper,`);
  lines.push(` * then performs a signed HTTP request with idempotency, retry on`);
  lines.push(` * 5xx/network errors with exponential backoff, and a per-attempt`);
  lines.push(` * timeout. 4xx responses are not retried — they propagate.`);
  lines.push(` */`);
  lines.push(`export async function emit(input: unknown): Promise<void> {`);
  lines.push(`  const payload = await buildPayload(input);`);
  lines.push(`  const body = JSON.stringify(payload);`);
  lines.push(`  const idempotencyKey = randomUUID();`);
  lines.push(`  const signature = sign(body);`);
  lines.push(``);
  lines.push(`  let lastErr: unknown;`);
  lines.push(`  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {`);
  lines.push(`    const controller = new AbortController();`);
  lines.push(`    const t = setTimeout(() => controller.abort(), TIMEOUT_MS);`);
  lines.push(`    try {`);
  lines.push(`      const res = await fetch(WEBHOOK_URL, {`);
  lines.push(`        method: ${JSON.stringify(method)},`);
  lines.push(`        body,`);
  lines.push(`        signal: controller.signal,`);
  lines.push(`        headers: {`);
  lines.push(`          "content-type": "application/json",`);
  lines.push(`          "x-signature": signature,`);
  lines.push(`          "x-idempotency-key": idempotencyKey,`);
  lines.push(`        },`);
  lines.push(`      });`);
  lines.push(`      if (res.ok) return;`);
  lines.push(`      // 4xx: client error — don't retry, but consume body for debugging.`);
  lines.push(`      if (res.status >= 400 && res.status < 500) {`);
  lines.push(`        throw new Error(\`webhook 4xx: \${res.status}\`);`);
  lines.push(`      }`);
  lines.push(`      lastErr = new Error(\`webhook \${res.status}\`);`);
  lines.push(`    } catch (err) {`);
  lines.push(`      lastErr = err;`);
  lines.push(`      // Network / abort errors get retried.`);
  lines.push(`    } finally {`);
  lines.push(`      clearTimeout(t);`);
  lines.push(`    }`);
  lines.push(`    if (attempt < MAX_ATTEMPTS) {`);
  lines.push(`      // Exponential backoff: 200ms, 400ms, 800ms…`);
  lines.push(`      await sleep(200 * 2 ** (attempt - 1));`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(`  throw lastErr;`);
  lines.push(`}`);
  return lines.join("\n") + "\n";
}

function buildInboundPrompt(
  ctx: GeneratorContext,
  receiverSrc: string,
  lang: ScaffoldLang,
  receiverFile: string,
  outputs: string[],
): string {
  const [processFile, testFile] = outputs;
  const lines: string[] = [];
  lines.push(buildServiceUserPrompt(ctx));
  lines.push("");
  lines.push("<hybrid-skeleton>");
  lines.push(
    `The HMAC-verifying webhook receiver (\`${receiverFile}\`) is already ` +
      `generated. Signature verification (timing-safe), body parsing, error ` +
      `response shaping, and 401/400/500 status mapping are all handled there. ` +
      `Your job is to write ONLY \`${processFile}\` (plus \`${testFile}\`) — ` +
      `do NOT regenerate \`${receiverFile}\`.`,
  );
  lines.push("");
  lines.push(`Here is the \`${receiverFile}\` you must match:`);
  lines.push("```" + fenceLang(lang));
  lines.push(receiverSrc.trimEnd());
  lines.push("```");
  lines.push("");
  lines.push(`Implement in \`${processFile}\`:`);
  lines.push(...inboundProcessRules(lang, testFile));
  lines.push("</hybrid-skeleton>");
  return lines.join("\n");
}

function inboundProcessRules(lang: ScaffoldLang, testFile: string): string[] {
  const common = [
    " - Validate the payload shape. Throw on mismatch — receiver maps the exception to 500.",
    " - Dispatch to the downstream nodes listed in `<outbound-edges>` using the clients in",
    "   `<available-clients>`. Use durable enqueueing (not in-memory) where possible.",
    ` - Tests in \`${testFile}\` cover: valid payload happy path, schema mismatch, downstream error.`,
    " - Do NOT log payload contents at info level — they may contain PII.",
  ];
  switch (lang) {
    case "node":
      return [" - `export async function process(payload: unknown): Promise<void>`", ...common];
    case "python":
      return [" - `async def process(payload: Any) -> None`", ...common];
    case "go":
      return [
        " - `func Process(ctx context.Context, payload any) error` (exported, error-returning).",
        ...common,
      ];
  }
}

function buildOutboundPrompt(
  ctx: GeneratorContext,
  emitterSrc: string,
  lang: ScaffoldLang,
  emitterFile: string,
  outputs: string[],
): string {
  const [payloadFile, testFile] = outputs;
  const lines: string[] = [];
  lines.push(buildServiceUserPrompt(ctx));
  lines.push("");
  lines.push("<hybrid-skeleton>");
  lines.push(
    `The signed-and-retrying webhook emitter (\`${emitterFile}\`) is already ` +
      `generated. HMAC signing, idempotency-key generation, exponential ` +
      `backoff retry on 5xx/network, and per-attempt timeout are all ` +
      `handled there. Your job is to write ONLY \`${payloadFile}\` (plus ` +
      `\`${testFile}\`) — do NOT regenerate \`${emitterFile}\`.`,
  );
  lines.push("");
  lines.push(`Here is the \`${emitterFile}\` you must match:`);
  lines.push("```" + fenceLang(lang));
  lines.push(emitterSrc.trimEnd());
  lines.push("```");
  lines.push("");
  lines.push(`Implement in \`${payloadFile}\`:`);
  lines.push(...outboundPayloadRules(lang, testFile));
  lines.push("</hybrid-skeleton>");
  return lines.join("\n");
}

function outboundPayloadRules(lang: ScaffoldLang, testFile: string): string[] {
  const common = [
    " - Pure transform — no network calls or side effects.",
    " - Strip PII fields the third party doesn't need.",
    ` - Tests in \`${testFile}\` cover: typical input → expected output, missing-field handling.`,
  ];
  switch (lang) {
    case "node":
      return [
        " - `export async function buildPayload(input: unknown): Promise<unknown>`",
        ...common,
      ];
    case "python":
      return [" - `def build_payload(input_: Any) -> Any` (sync — emitter awaits if needed)", ...common];
    case "go":
      return [" - `func BuildPayload(input any) (any, error)` (exported, error-returning)", ...common];
  }
}

/**
 * Python inbound receiver — FastAPI with hmac.compare_digest for
 * timing-safe signature comparison.
 */
function renderInboundReceiverPython(ctx: GeneratorContext): string {
  const plan = ctx.node.plan ?? {};
  const method = (plan.method || "POST").toLowerCase();
  return [
    `"""HMAC-verifying webhook receiver for "${ctx.node.label}".`,
    ``,
    `Skeleton generated by Arkon buildout (deterministic).`,
    `Business logic in process.py is LLM-generated.`,
    `"""`,
    ``,
    `from __future__ import annotations`,
    ``,
    `import hashlib`,
    `import hmac`,
    `import json`,
    `import logging`,
    `import os`,
    `from typing import Any`,
    ``,
    `from fastapi import FastAPI, Request, Response`,
    ``,
    `from process import process as process_payload`,
    ``,
    `_WEBHOOK_SECRET = os.environ.get("WEBHOOK_SECRET")`,
    `if not _WEBHOOK_SECRET:`,
    `    raise RuntimeError("WEBHOOK_SECRET env var is required")`,
    ``,
    `_SIGNATURE_HEADER = os.environ.get("WEBHOOK_SIGNATURE_HEADER", "x-signature").lower()`,
    ``,
    `app = FastAPI()`,
    `log = logging.getLogger(__name__)`,
    ``,
    `def verify_signature(raw_body: bytes, signature: str | None) -> bool:`,
    `    """Constant-time HMAC-SHA256 verification."""`,
    `    if signature is None:`,
    `        return False`,
    `    expected = hmac.new(_WEBHOOK_SECRET.encode(), raw_body, hashlib.sha256).hexdigest()`,
    `    provided = signature[7:] if signature.startswith("sha256=") else signature`,
    `    if len(provided) != len(expected):`,
    `        return False`,
    `    return hmac.compare_digest(expected, provided)`,
    ``,
    `@app.${method}("/")`,
    `async def handle(request: Request) -> Response:`,
    `    raw = await request.body()`,
    `    sig = request.headers.get(_SIGNATURE_HEADER)`,
    `    if not verify_signature(raw, sig):`,
    `        return Response(`,
    `            content=json.dumps({"error": "invalid_signature"}),`,
    `            status_code=401,`,
    `            media_type="application/json",`,
    `        )`,
    `    try:`,
    `        payload: Any = json.loads(raw) if raw else None`,
    `    except json.JSONDecodeError:`,
    `        return Response(`,
    `            content=json.dumps({"error": "invalid_json"}),`,
    `            status_code=400,`,
    `            media_type="application/json",`,
    `        )`,
    `    try:`,
    `        await process_payload(payload)`,
    `        return Response(status_code=200)`,
    `    except Exception:`,
    `        # Don't echo internal detail back to the caller — log fully server-side.`,
    `        log.exception("webhook process failed")`,
    `        return Response(`,
    `            content=json.dumps({"error": "internal_error"}),`,
    `            status_code=500,`,
    `            media_type="application/json",`,
    `        )`,
    ``,
  ].join("\n");
}

/**
 * Python outbound emitter — httpx async client with HMAC + idempotency
 * key + exponential backoff retry. AsyncClient handles per-attempt
 * timeout.
 */
function renderOutboundEmitterPython(ctx: GeneratorContext): string {
  const plan = ctx.node.plan ?? {};
  const url = plan.url || "https://example.com/webhook";
  const method = (plan.method || "POST").toUpperCase();
  return [
    `"""Signed-and-retrying webhook emitter for "${ctx.node.label}".`,
    ``,
    `Skeleton generated by Arkon buildout (deterministic).`,
    `Payload mapping in payload.py is LLM-generated.`,
    `"""`,
    ``,
    `from __future__ import annotations`,
    ``,
    `import asyncio`,
    `import hashlib`,
    `import hmac`,
    `import json`,
    `import logging`,
    `import os`,
    `import uuid`,
    `from typing import Any`,
    ``,
    `import httpx`,
    ``,
    `from payload import build_payload`,
    ``,
    `_WEBHOOK_URL = os.environ.get("WEBHOOK_URL", ${JSON.stringify(url)})`,
    `_WEBHOOK_SECRET = os.environ.get("WEBHOOK_SECRET")`,
    `if not _WEBHOOK_SECRET:`,
    `    raise RuntimeError("WEBHOOK_SECRET env var is required")`,
    ``,
    `_TIMEOUT_S = float(os.environ.get("WEBHOOK_TIMEOUT_S", "5.0"))`,
    `_MAX_ATTEMPTS = int(os.environ.get("WEBHOOK_MAX_ATTEMPTS", "3"))`,
    ``,
    `log = logging.getLogger(__name__)`,
    ``,
    `def _sign(body: bytes) -> str:`,
    `    return hmac.new(_WEBHOOK_SECRET.encode(), body, hashlib.sha256).hexdigest()`,
    ``,
    `async def emit(input_: Any) -> None:`,
    `    """Compute payload, sign, POST with retry on 5xx/network."""`,
    `    result = build_payload(input_)`,
    `    if asyncio.iscoroutine(result):`,
    `        result = await result`,
    `    body = json.dumps(result).encode()`,
    `    headers = {`,
    `        "content-type": "application/json",`,
    `        "x-signature": _sign(body),`,
    `        "x-idempotency-key": str(uuid.uuid4()),`,
    `    }`,
    ``,
    `    last_err: Exception | None = None`,
    `    async with httpx.AsyncClient(timeout=_TIMEOUT_S) as client:`,
    `        for attempt in range(1, _MAX_ATTEMPTS + 1):`,
    `            try:`,
    `                resp = await client.request(${JSON.stringify(method)}, _WEBHOOK_URL, content=body, headers=headers)`,
    `                if 200 <= resp.status_code < 300:`,
    `                    return`,
    `                if 400 <= resp.status_code < 500:`,
    `                    raise RuntimeError(f"webhook 4xx: {resp.status_code}")`,
    `                last_err = RuntimeError(f"webhook {resp.status_code}")`,
    `            except (httpx.NetworkError, httpx.TimeoutException) as err:`,
    `                last_err = err`,
    `            if attempt < _MAX_ATTEMPTS:`,
    `                # Exponential backoff: 200ms, 400ms, 800ms…`,
    `                await asyncio.sleep(0.2 * (2 ** (attempt - 1)))`,
    `    assert last_err is not None`,
    `    raise last_err`,
    ``,
  ].join("\n");
}

/**
 * Go inbound receiver — net/http handler with hmac.Equal-style
 * timing-safe comparison via subtle.ConstantTimeCompare.
 */
function renderInboundReceiverGo(ctx: GeneratorContext): string {
  const plan = ctx.node.plan ?? {};
  const method = (plan.method || "POST").toUpperCase();
  return [
    `// Package webhook — HMAC-verifying receiver for "${ctx.node.label}".`,
    `//`,
    `// Skeleton generated by Arkon buildout (deterministic).`,
    `// Business logic in process.go is LLM-generated.`,
    `package webhook`,
    ``,
    `import (`,
    `	"crypto/hmac"`,
    `	"crypto/sha256"`,
    `	"crypto/subtle"`,
    `	"encoding/hex"`,
    `	"encoding/json"`,
    `	"io"`,
    `	"log"`,
    `	"net/http"`,
    `	"os"`,
    `	"strings"`,
    `)`,
    ``,
    `var (`,
    `	webhookSecret   = mustEnv("WEBHOOK_SECRET")`,
    `	signatureHeader = envOr("WEBHOOK_SIGNATURE_HEADER", "X-Signature")`,
    `)`,
    ``,
    `func mustEnv(k string) string {`,
    `	v := os.Getenv(k)`,
    `	if v == "" {`,
    `		panic(k + " env var is required")`,
    `	}`,
    `	return v`,
    `}`,
    ``,
    `func envOr(k, def string) string {`,
    `	if v := os.Getenv(k); v != "" {`,
    `		return v`,
    `	}`,
    `	return def`,
    `}`,
    ``,
    `// VerifySignature performs a constant-time HMAC-SHA256 verification.`,
    `// Returns true on match, false on any failure (including parse).`,
    `func VerifySignature(rawBody []byte, signature string) bool {`,
    `	if signature == "" {`,
    `		return false`,
    `	}`,
    `	provided := strings.TrimPrefix(signature, "sha256=")`,
    `	providedBytes, err := hex.DecodeString(provided)`,
    `	if err != nil {`,
    `		return false`,
    `	}`,
    `	mac := hmac.New(sha256.New, []byte(webhookSecret))`,
    `	mac.Write(rawBody)`,
    `	expected := mac.Sum(nil)`,
    `	return subtle.ConstantTimeCompare(expected, providedBytes) == 1`,
    `}`,
    ``,
    `// Handle is the HTTP handler. Wire it into http.ServeMux yourself —`,
    `// e.g. mux.HandleFunc("POST /webhook", webhook.Handle).`,
    `func Handle(w http.ResponseWriter, r *http.Request) {`,
    `	if r.Method != ${JSON.stringify(method)} {`,
    `		w.WriteHeader(http.StatusMethodNotAllowed)`,
    `		return`,
    `	}`,
    `	raw, err := io.ReadAll(r.Body)`,
    `	if err != nil {`,
    `		w.WriteHeader(http.StatusBadRequest)`,
    `		return`,
    `	}`,
    `	sig := r.Header.Get(signatureHeader)`,
    `	if !VerifySignature(raw, sig) {`,
    `		writeJSON(w, http.StatusUnauthorized, map[string]string{"error": "invalid_signature"})`,
    `		return`,
    `	}`,
    `	var payload any`,
    `	if len(raw) > 0 {`,
    `		if err := json.Unmarshal(raw, &payload); err != nil {`,
    `			writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid_json"})`,
    `			return`,
    `		}`,
    `	}`,
    `	if err := Process(r.Context(), payload); err != nil {`,
    `		log.Printf("webhook process failed: %v", err)`,
    `		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "internal_error"})`,
    `		return`,
    `	}`,
    `	w.WriteHeader(http.StatusOK)`,
    `}`,
    ``,
    `func writeJSON(w http.ResponseWriter, status int, body any) {`,
    `	w.Header().Set("content-type", "application/json")`,
    `	w.WriteHeader(status)`,
    `	_ = json.NewEncoder(w).Encode(body)`,
    `}`,
    ``,
  ].join("\n");
}

/**
 * Go outbound emitter — http.Client with context timeout, exponential
 * backoff retry, idempotency key.
 */
function renderOutboundEmitterGo(ctx: GeneratorContext): string {
  const plan = ctx.node.plan ?? {};
  const url = plan.url || "https://example.com/webhook";
  const method = (plan.method || "POST").toUpperCase();
  return [
    `// Package webhook — signed-and-retrying emitter for "${ctx.node.label}".`,
    `//`,
    `// Skeleton generated by Arkon buildout (deterministic).`,
    `// Payload mapping in payload.go is LLM-generated.`,
    `package webhook`,
    ``,
    `import (`,
    `	"bytes"`,
    `	"context"`,
    `	"crypto/hmac"`,
    `	"crypto/sha256"`,
    `	"encoding/hex"`,
    `	"encoding/json"`,
    `	"errors"`,
    `	"fmt"`,
    `	"net/http"`,
    `	"os"`,
    `	"strconv"`,
    `	"time"`,
    ``,
    `	"github.com/google/uuid"`,
    `)`,
    ``,
    `var (`,
    `	webhookURL      = envOrDefault("WEBHOOK_URL", ${JSON.stringify(url)})`,
    `	emitterSecret   = mustEnvEmit("WEBHOOK_SECRET")`,
    `	emitTimeout     = envDuration("WEBHOOK_TIMEOUT_MS", 5000) * time.Millisecond`,
    `	emitMaxAttempts = envInt("WEBHOOK_MAX_ATTEMPTS", 3)`,
    `)`,
    ``,
    `func mustEnvEmit(k string) string {`,
    `	v := os.Getenv(k)`,
    `	if v == "" {`,
    `		panic(k + " env var is required")`,
    `	}`,
    `	return v`,
    `}`,
    ``,
    `func envOrDefault(k, def string) string {`,
    `	if v := os.Getenv(k); v != "" {`,
    `		return v`,
    `	}`,
    `	return def`,
    `}`,
    ``,
    `func envInt(k string, def int) int {`,
    `	if v := os.Getenv(k); v != "" {`,
    `		if n, err := strconv.Atoi(v); err == nil {`,
    `			return n`,
    `		}`,
    `	}`,
    `	return def`,
    `}`,
    ``,
    `func envDuration(k string, defMs int) time.Duration {`,
    `	return time.Duration(envInt(k, defMs))`,
    `}`,
    ``,
    `func sign(body []byte) string {`,
    `	mac := hmac.New(sha256.New, []byte(emitterSecret))`,
    `	mac.Write(body)`,
    `	return hex.EncodeToString(mac.Sum(nil))`,
    `}`,
    ``,
    `// Emit serializes the payload, signs it, posts with retry. 5xx and`,
    `// network errors retry with exponential backoff; 4xx propagates.`,
    `func Emit(ctx context.Context, input any) error {`,
    `	mapped, err := BuildPayload(input)`,
    `	if err != nil {`,
    `		return fmt.Errorf("build payload: %w", err)`,
    `	}`,
    `	body, err := json.Marshal(mapped)`,
    `	if err != nil {`,
    `		return fmt.Errorf("marshal: %w", err)`,
    `	}`,
    `	idempotencyKey := uuid.NewString()`,
    `	signature := sign(body)`,
    ``,
    `	client := &http.Client{Timeout: emitTimeout}`,
    `	var lastErr error`,
    `	for attempt := 1; attempt <= emitMaxAttempts; attempt++ {`,
    `		req, err := http.NewRequestWithContext(ctx, ${JSON.stringify(method)}, webhookURL, bytes.NewReader(body))`,
    `		if err != nil {`,
    `			return err`,
    `		}`,
    `		req.Header.Set("content-type", "application/json")`,
    `		req.Header.Set("x-signature", signature)`,
    `		req.Header.Set("x-idempotency-key", idempotencyKey)`,
    ``,
    `		resp, err := client.Do(req)`,
    `		if err == nil {`,
    `			resp.Body.Close()`,
    `			if resp.StatusCode >= 200 && resp.StatusCode < 300 {`,
    `				return nil`,
    `			}`,
    `			if resp.StatusCode >= 400 && resp.StatusCode < 500 {`,
    `				return fmt.Errorf("webhook 4xx: %d", resp.StatusCode)`,
    `			}`,
    `			lastErr = fmt.Errorf("webhook %d", resp.StatusCode)`,
    `		} else {`,
    `			lastErr = err`,
    `		}`,
    `		if attempt < emitMaxAttempts {`,
    `			backoff := time.Duration(200*(1<<(attempt-1))) * time.Millisecond`,
    `			select {`,
    `			case <-time.After(backoff):`,
    `			case <-ctx.Done():`,
    `				return ctx.Err()`,
    `			}`,
    `		}`,
    `	}`,
    `	if lastErr == nil {`,
    `		lastErr = errors.New("all retries exhausted")`,
    `	}`,
    `	return lastErr`,
    `}`,
    ``,
  ].join("\n");
}
