/**
 * Vendor-agnostic bundle emitter.
 *
 * Each LLM-driven node produces a "bundle" — a folder containing:
 *
 *   README.md     — usage instructions across common toolchains
 *   prompt.md     — the full prompt (system + user merged)
 *   validate.sh   — post-generation language-specific check
 *
 * The bundle is the contract. Whatever tool the user prefers — Claude Code,
 * Cursor, ChatGPT, a raw API call, a local model — they feed prompt.md to
 * it and save the produced files into the same folder, then run
 * validate.sh to catch obvious breakage.
 *
 * Why bundles instead of calling the LLM directly:
 *  - Arkon never handles an API key. Zero credential management in the
 *    web UI; no localStorage modal, no Settings entry, no audit burden.
 *  - Vendor-neutral. Works with any model, paid or local.
 *  - Composes with existing AI workflows people already use.
 *  - Reviewable: the user can read and edit the prompt before running it.
 *
 * Tradeoff: the "I just want it built" user takes one extra step (run
 * the bundle in their tool of choice). Mitigated by the dev-only
 * `scripts/buildout.ts --execute` path that drives bundles through
 * Anthropic for smoke testing — not part of the product surface.
 */

import type { GeneratorContext, GeneratedFile } from "./types";
import type { ScaffoldLang } from "../scaffold/concerns/types";

export interface BundleSpec {
  /** Stable, cache-eligible system prompt (built by callers). */
  systemPrompt: string;
  /** Per-node user prompt (built by callers). */
  userPrompt: string;
  /**
   * Optional list of expected output file paths (relative to the bundle
   * folder). Surfaced in the prompt so the LLM knows what to produce,
   * and used by validate.sh to check the right files exist.
   */
  expectedOutputs?: string[];
}

interface LanguageValidator {
  /** File extensions to validate. */
  exts: string[];
  /** Shell snippet to run from the bundle folder. */
  script: string;
}

const LANGUAGE_VALIDATORS: Record<ScaffoldLang, LanguageValidator> = {
  node: {
    exts: [".ts", ".tsx", ".js"],
    script: [
      "# Type-check TypeScript output. Server skeletons import from node:* so we",
      "# include the 'node' types lib explicitly — make sure @types/node is",
      "# installed in the parent project (or run this from within one).",
      "if compgen -G '*.ts' > /dev/null; then",
      "  if command -v tsc >/dev/null 2>&1; then",
      "    tsc --noEmit --strict --skipLibCheck --target ES2022 --module ESNext --moduleResolution Bundler --types node *.ts || exit 1",
      "  else",
      "    echo 'tsc not on PATH — skipping typecheck' >&2",
      "  fi",
      "fi",
      "",
      "# Run tests if vitest is available.",
      "if compgen -G '*.test.ts' > /dev/null && command -v vitest >/dev/null 2>&1; then",
      "  vitest run --reporter=dot || exit 1",
      "fi",
    ].join("\n"),
  },
  python: {
    exts: [".py"],
    script: [
      "# Syntax-check generated Python.",
      "if compgen -G '*.py' > /dev/null; then",
      "  python3 -m compileall -q *.py || exit 1",
      "fi",
      "",
      "# Run tests if pytest is available.",
      "if compgen -G 'test_*.py' > /dev/null && command -v pytest >/dev/null 2>&1; then",
      "  pytest -q || exit 1",
      "fi",
    ].join("\n"),
  },
  go: {
    exts: [".go"],
    script: [
      "# Vet generated Go.",
      "if compgen -G '*.go' > /dev/null; then",
      "  go vet ./... || exit 1",
      "fi",
      "",
      "# Run tests.",
      "if compgen -G '*_test.go' > /dev/null; then",
      "  go test ./... || exit 1",
      "fi",
    ].join("\n"),
  },
};

/**
 * Render the bundle: README.md + prompt.md + validate.sh.
 *
 * Generators call this in place of a direct LLM invocation.
 */
export function emitBundle(ctx: GeneratorContext, spec: BundleSpec): GeneratedFile[] {
  const lang = ctx.language ?? "node";
  return [
    { path: "README.md", contents: renderReadme(ctx, spec, lang) },
    { path: "prompt.md", contents: renderPrompt(ctx, spec) },
    { path: "validate.sh", contents: renderValidator(lang) },
  ];
}

function renderPrompt(ctx: GeneratorContext, spec: BundleSpec): string {
  const lines: string[] = [];
  lines.push(`# Build prompt: ${ctx.node.label}`);
  lines.push(``);
  lines.push(
    `This prompt was generated by Arkon. Feed it to any code-generating LLM ` +
      `(Claude, GPT, Gemini, local model, etc.) and save the produced files ` +
      `into this bundle's directory.`,
  );
  lines.push(``);
  lines.push(`---`);
  lines.push(``);
  lines.push(`## System`);
  lines.push(``);
  lines.push(spec.systemPrompt);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);
  lines.push(`## Task`);
  lines.push(``);
  lines.push(spec.userPrompt);
  if (spec.expectedOutputs && spec.expectedOutputs.length > 0) {
    lines.push(``);
    lines.push(`---`);
    lines.push(``);
    lines.push(`## Expected output files`);
    lines.push(``);
    for (const f of spec.expectedOutputs) lines.push(`- \`${f}\``);
  }
  return lines.join("\n") + "\n";
}

function renderReadme(ctx: GeneratorContext, spec: BundleSpec, lang: ScaffoldLang): string {
  void spec;
  return `# ${ctx.node.label} — build bundle

This bundle contains a self-contained prompt for generating the implementation of the **${ctx.node.componentType}** node \`${ctx.node.label}\` from the Arkon canvas.

Target language: **${langDisplay(lang)}**.

## Files

| File          | Purpose                                                    |
|---------------|------------------------------------------------------------|
| \`prompt.md\`   | The prompt. Self-contained — feed verbatim to your model.  |
| \`validate.sh\` | Post-generation check (typecheck + tests where possible).  |
| \`README.md\`   | This file.                                                 |

## How to run

Pick the path that matches your toolchain. **Save every file your model produces into this bundle's directory.**

### Claude Code (recommended)
\`\`\`sh
claude < prompt.md
\`\`\`

### Cursor / Windsurf / Continue
Open this directory in your IDE. Paste the contents of \`prompt.md\` as your message.

### Claude.ai / ChatGPT / Gemini (web)
Copy \`prompt.md\` into the chat. For each file the model emits, save it next to this README at the path it specifies.

### Anthropic API (raw)
\`\`\`sh
curl https://api.anthropic.com/v1/messages \\
  -H "x-api-key: $ANTHROPIC_API_KEY" \\
  -H "anthropic-version: 2023-06-01" \\
  -H "content-type: application/json" \\
  -d "$(jq -Rs '{model:"claude-opus-4-7",max_tokens:32768,messages:[{role:"user",content:.}]}' < prompt.md)"
\`\`\`

### OpenAI API (raw)
\`\`\`sh
curl https://api.openai.com/v1/chat/completions \\
  -H "Authorization: Bearer $OPENAI_API_KEY" \\
  -H "content-type: application/json" \\
  -d "$(jq -Rs '{model:"gpt-4o",messages:[{role:"user",content:.}]}' < prompt.md)"
\`\`\`

### Local (Ollama, llama.cpp, vLLM)
\`\`\`sh
ollama run codellama < prompt.md
\`\`\`

## After generation

1. Confirm every file the model emitted lives in this directory.
2. Run \`./validate.sh\` to typecheck and run tests where possible.
3. Commit.

## Regenerating

If you change the node's description or its edges on the canvas and re-run the Arkon build, \`prompt.md\` updates. Re-run your LLM of choice to refresh the generated files.
`;
}

function renderValidator(lang: ScaffoldLang): string {
  const v = LANGUAGE_VALIDATORS[lang];
  return [
    "#!/usr/bin/env bash",
    "# Auto-generated by Arkon. Edit if your project has a specific test runner.",
    "set -euo pipefail",
    "cd \"$(dirname \"$0\")\"",
    "",
    v.script,
    "",
    "echo '✓ validate.sh passed'",
  ].join("\n") + "\n";
}

function langDisplay(lang: ScaffoldLang): string {
  switch (lang) {
    case "node":
      return "TypeScript (Node.js)";
    case "python":
      return "Python";
    case "go":
      return "Go";
  }
}
