import type { PatternDefinition } from "./types";

export const BUILTIN_PATTERNS: PatternDefinition[] = [
  {
    id: "cache-aside",
    name: "Cache-Aside",
    description: "Service checks cache before hitting database",
    icon: "M13 2L3 14h9l-1 8 10-12h-9l1-8",
    color: "#a855f7",
    source: "builtin",
    nodes: [
      { localId: "svc", componentType: "service", relativePosition: { x: 0, y: 0 } },
      { localId: "cache", componentType: "cache", relativePosition: { x: 280, y: -100 } },
      { localId: "db", componentType: "database", relativePosition: { x: 280, y: 100 } },
    ],
    edges: [
      { sourceLocalId: "svc", targetLocalId: "cache", label: "check" },
      { sourceLocalId: "svc", targetLocalId: "db", label: "fallback" },
    ],
  },
  {
    id: "cqrs",
    name: "CQRS",
    description: "Separate command and query paths with event sync",
    icon: "M16 3h5v5M4 20L21 3M21 16v5h-5M15 15l6 6M4 4l5 5",
    color: "#6366f1",
    source: "builtin",
    nodes: [
      { localId: "gw", componentType: "api-gateway", relativePosition: { x: 0, y: 0 } },
      { localId: "cmd-svc", componentType: "service", relativePosition: { x: 280, y: -100 } },
      { localId: "write-db", componentType: "database", relativePosition: { x: 560, y: -100 } },
      { localId: "mq", componentType: "message-queue", relativePosition: { x: 560, y: 0 } },
      { localId: "qry-svc", componentType: "service", relativePosition: { x: 280, y: 100 } },
      { localId: "read-db", componentType: "database", relativePosition: { x: 560, y: 100 } },
    ],
    edges: [
      { sourceLocalId: "gw", targetLocalId: "cmd-svc", label: "commands" },
      { sourceLocalId: "gw", targetLocalId: "qry-svc", label: "queries" },
      { sourceLocalId: "cmd-svc", targetLocalId: "write-db", label: "write" },
      { sourceLocalId: "cmd-svc", targetLocalId: "mq", label: "events" },
      { sourceLocalId: "mq", targetLocalId: "qry-svc", label: "sync" },
      { sourceLocalId: "qry-svc", targetLocalId: "read-db", label: "read" },
    ],
  },
  {
    id: "pubsub-fanout",
    name: "Pub/Sub Fanout",
    description: "One producer fans out to multiple consumers via queue",
    icon: "M22 2L11 13M22 2l-7 20-4-9-9-4 20-7z",
    color: "#eab308",
    source: "builtin",
    nodes: [
      { localId: "producer", componentType: "service", relativePosition: { x: 0, y: 0 } },
      { localId: "mq", componentType: "message-queue", relativePosition: { x: 280, y: 0 } },
      { localId: "consumer1", componentType: "service", relativePosition: { x: 560, y: -160 } },
      { localId: "consumer2", componentType: "service", relativePosition: { x: 560, y: 0 } },
      { localId: "consumer3", componentType: "service", relativePosition: { x: 560, y: 160 } },
    ],
    edges: [
      { sourceLocalId: "producer", targetLocalId: "mq", label: "publish" },
      { sourceLocalId: "mq", targetLocalId: "consumer1", label: "subscribe" },
      { sourceLocalId: "mq", targetLocalId: "consumer2", label: "subscribe" },
      { sourceLocalId: "mq", targetLocalId: "consumer3", label: "subscribe" },
    ],
  },
  {
    id: "load-balanced-api",
    name: "Load-Balanced API",
    description: "Load balancer distributes traffic across service replicas",
    icon: "M12 2v20M2 12h20M12 2a10 10 0 0110 10M12 2a10 10 0 00-10 10",
    color: "#3b82f6",
    source: "builtin",
    nodes: [
      { localId: "lb", componentType: "load-balancer", relativePosition: { x: 0, y: 0 } },
      { localId: "svc1", componentType: "service", relativePosition: { x: 280, y: -160 } },
      { localId: "svc2", componentType: "service", relativePosition: { x: 280, y: 0 } },
      { localId: "svc3", componentType: "service", relativePosition: { x: 280, y: 160 } },
      { localId: "db", componentType: "database", relativePosition: { x: 560, y: 0 } },
    ],
    edges: [
      { sourceLocalId: "lb", targetLocalId: "svc1" },
      { sourceLocalId: "lb", targetLocalId: "svc2" },
      { sourceLocalId: "lb", targetLocalId: "svc3" },
      { sourceLocalId: "svc1", targetLocalId: "db" },
      { sourceLocalId: "svc2", targetLocalId: "db" },
      { sourceLocalId: "svc3", targetLocalId: "db" },
    ],
  },
  {
    id: "cdn-origin",
    name: "CDN + Origin",
    description: "DNS routes to CDN backed by object storage",
    icon: "M12 2a10 10 0 100 20 10 10 0 000-20zM2 12h20M12 2a15.3 15.3 0 014 10 15.3 15.3 0 01-4 10 15.3 15.3 0 01-4-10 15.3 15.3 0 014-10z",
    color: "#ec4899",
    source: "builtin",
    nodes: [
      { localId: "dns", componentType: "dns", relativePosition: { x: 0, y: 0 } },
      { localId: "cdn", componentType: "cdn", relativePosition: { x: 280, y: 0 } },
      { localId: "storage", componentType: "storage", relativePosition: { x: 560, y: 0 } },
    ],
    edges: [
      { sourceLocalId: "dns", targetLocalId: "cdn", label: "resolve" },
      { sourceLocalId: "cdn", targetLocalId: "storage", label: "origin pull" },
    ],
  },
  {
    id: "auth-gateway",
    name: "Auth Gateway",
    description: "API gateway authenticates via dedicated auth service",
    icon: "M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z",
    color: "#ef4444",
    source: "builtin",
    nodes: [
      { localId: "gw", componentType: "api-gateway", relativePosition: { x: 0, y: 0 } },
      { localId: "auth", componentType: "service", relativePosition: { x: 280, y: -80 } },
      { localId: "db", componentType: "database", relativePosition: { x: 560, y: -80 } },
      { localId: "svc", componentType: "service", relativePosition: { x: 280, y: 80 } },
    ],
    edges: [
      { sourceLocalId: "gw", targetLocalId: "auth", label: "authenticate" },
      { sourceLocalId: "auth", targetLocalId: "db", label: "verify" },
      { sourceLocalId: "gw", targetLocalId: "svc", label: "forward" },
    ],
  },
  {
    id: "event-sourcing",
    name: "Event Sourcing",
    description: "Service emits events to stream processor for materialized views",
    icon: "M4 4h16v4H4zM4 10h16v4H4zM4 16h16v4H4z",
    color: "#10b981",
    source: "builtin",
    nodes: [
      { localId: "svc", componentType: "service", relativePosition: { x: 0, y: 0 } },
      {
        localId: "stream",
        componentType: "stream-processor",
        relativePosition: { x: 280, y: 0 },
      },
      { localId: "db", componentType: "database", relativePosition: { x: 560, y: -80 } },
      {
        localId: "search",
        componentType: "search-engine",
        relativePosition: { x: 560, y: 80 },
      },
    ],
    edges: [
      { sourceLocalId: "svc", targetLocalId: "stream", label: "events" },
      { sourceLocalId: "stream", targetLocalId: "db", label: "store" },
      { sourceLocalId: "stream", targetLocalId: "search", label: "index" },
    ],
  },
  {
    id: "microservice-sidecar",
    name: "Microservice + Sidecar",
    description: "API gateway to service backed by cache, database, and queue",
    icon: "M21 16V8a2 2 0 00-1-1.73l-7-4a2 2 0 00-2 0l-7 4A2 2 0 003 8v8a2 2 0 001 1.73l7 4a2 2 0 002 0l7-4A2 2 0 0021 16z",
    color: "#22c55e",
    source: "builtin",
    nodes: [
      { localId: "gw", componentType: "api-gateway", relativePosition: { x: 0, y: 0 } },
      { localId: "svc", componentType: "service", relativePosition: { x: 280, y: 0 } },
      { localId: "cache", componentType: "cache", relativePosition: { x: 560, y: -160 } },
      { localId: "db", componentType: "database", relativePosition: { x: 560, y: 0 } },
      { localId: "mq", componentType: "message-queue", relativePosition: { x: 560, y: 160 } },
    ],
    edges: [
      { sourceLocalId: "gw", targetLocalId: "svc", label: "route" },
      { sourceLocalId: "svc", targetLocalId: "cache", label: "cache" },
      { sourceLocalId: "svc", targetLocalId: "db", label: "persist" },
      { sourceLocalId: "svc", targetLocalId: "mq", label: "emit" },
    ],
  },
  {
    id: "client-backend",
    name: "Client Full Stack",
    description: "Client through DNS, load balancer to service and database",
    icon: "M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2M12 3a4 4 0 100 8 4 4 0 000-8z",
    color: "#f59e0b",
    source: "builtin",
    nodes: [
      { localId: "client", componentType: "client", relativePosition: { x: 0, y: 0 } },
      { localId: "dns", componentType: "dns", relativePosition: { x: 250, y: 0 } },
      {
        localId: "lb",
        componentType: "load-balancer",
        relativePosition: { x: 500, y: 0 },
      },
      { localId: "svc", componentType: "service", relativePosition: { x: 750, y: 0 } },
      { localId: "db", componentType: "database", relativePosition: { x: 1000, y: 0 } },
    ],
    edges: [
      { sourceLocalId: "client", targetLocalId: "dns", label: "resolve" },
      { sourceLocalId: "dns", targetLocalId: "lb" },
      { sourceLocalId: "lb", targetLocalId: "svc" },
      { sourceLocalId: "svc", targetLocalId: "db" },
    ],
  },
  {
    id: "etl-pipeline",
    name: "ETL Pipeline",
    description: "Cron triggers serverless ETL from database to warehouse",
    icon: "M12 2a10 10 0 100 20 10 10 0 000-20zM12 6v6l4 2",
    color: "#8b5cf6",
    source: "builtin",
    nodes: [
      { localId: "cron", componentType: "cron", relativePosition: { x: 0, y: 0 } },
      { localId: "fn", componentType: "serverless", relativePosition: { x: 280, y: 0 } },
      {
        localId: "source-db",
        componentType: "database",
        relativePosition: { x: 560, y: -80 },
      },
      {
        localId: "warehouse",
        componentType: "data-warehouse",
        relativePosition: { x: 560, y: 80 },
      },
    ],
    edges: [
      { sourceLocalId: "cron", targetLocalId: "fn", label: "trigger" },
      { sourceLocalId: "fn", targetLocalId: "source-db", label: "extract" },
      { sourceLocalId: "fn", targetLocalId: "warehouse", label: "load" },
    ],
  },
];
